//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.03.11 at 12:27:12 AM CET 
//


package jxml;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for AppealEventCodeType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="AppealEventCodeType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}token">
 *     &lt;enumeration value="Appeal filed"/>
 *     &lt;enumeration value="Admissibility checked"/>
 *     &lt;enumeration value="First waiting for appellant's response"/>
 *     &lt;enumeration value="Second waiting for appellant's response"/>
 *     &lt;enumeration value="First waiting for respondent's response"/>
 *     &lt;enumeration value="Second waiting for respondent's response"/>
 *     &lt;enumeration value="Designation of rapporteur done"/>
 *     &lt;enumeration value="Oral procedure pending"/>
 *     &lt;enumeration value="Rapport sent to parties"/>
 *     &lt;enumeration value="Decision rendered and notified"/>
 *     &lt;enumeration value="Appeal with the Court of Justice pending"/>
 *     &lt;enumeration value="Final decision - Appeal withdrawn"/>
 *     &lt;enumeration value="Final decision  Appeal rejected"/>
 *     &lt;enumeration value="Final decision  Appeal rejected in part"/>
 *     &lt;enumeration value="No decision  Appeal not duly entered"/>
 *     &lt;enumeration value="No decision  ex parte"/>
 *     &lt;enumeration value="No decision  inter partes"/>
 *     &lt;enumeration value="Appeal closed"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "AppealEventCodeType")
@XmlEnum
public enum AppealEventCodeType {

    @XmlEnumValue("Appeal filed")
    APPEAL_FILED("Appeal filed"),
    @XmlEnumValue("Admissibility checked")
    ADMISSIBILITY_CHECKED("Admissibility checked"),
    @XmlEnumValue("First waiting for appellant's response")
    FIRST_WAITING_FOR_APPELLANT_S_RESPONSE("First waiting for appellant's response"),
    @XmlEnumValue("Second waiting for appellant's response")
    SECOND_WAITING_FOR_APPELLANT_S_RESPONSE("Second waiting for appellant's response"),
    @XmlEnumValue("First waiting for respondent's response")
    FIRST_WAITING_FOR_RESPONDENT_S_RESPONSE("First waiting for respondent's response"),
    @XmlEnumValue("Second waiting for respondent's response")
    SECOND_WAITING_FOR_RESPONDENT_S_RESPONSE("Second waiting for respondent's response"),
    @XmlEnumValue("Designation of rapporteur done")
    DESIGNATION_OF_RAPPORTEUR_DONE("Designation of rapporteur done"),
    @XmlEnumValue("Oral procedure pending")
    ORAL_PROCEDURE_PENDING("Oral procedure pending"),
    @XmlEnumValue("Rapport sent to parties")
    RAPPORT_SENT_TO_PARTIES("Rapport sent to parties"),
    @XmlEnumValue("Decision rendered and notified")
    DECISION_RENDERED_AND_NOTIFIED("Decision rendered and notified"),
    @XmlEnumValue("Appeal with the Court of Justice pending")
    APPEAL_WITH_THE_COURT_OF_JUSTICE_PENDING("Appeal with the Court of Justice pending"),
    @XmlEnumValue("Final decision - Appeal withdrawn")
    FINAL_DECISION_APPEAL_WITHDRAWN("Final decision - Appeal withdrawn"),
    @XmlEnumValue("Final decision  Appeal rejected")
    FINAL_DECISION_APPEAL_REJECTED("Final decision  Appeal rejected"),
    @XmlEnumValue("Final decision  Appeal rejected in part")
    FINAL_DECISION_APPEAL_REJECTED_IN_PART("Final decision  Appeal rejected in part"),
    @XmlEnumValue("No decision  Appeal not duly entered")
    NO_DECISION_APPEAL_NOT_DULY_ENTERED("No decision  Appeal not duly entered"),
    @XmlEnumValue("No decision  ex parte")
    NO_DECISION_EX_PARTE("No decision  ex parte"),
    @XmlEnumValue("No decision  inter partes")
    NO_DECISION_INTER_PARTES("No decision  inter partes"),
    @XmlEnumValue("Appeal closed")
    APPEAL_CLOSED("Appeal closed");
    private final String value;

    AppealEventCodeType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static AppealEventCodeType fromValue(String v) {
        for (AppealEventCodeType c: AppealEventCodeType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
