//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.03.11 at 12:27:12 AM CET 
//


package jxml;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for AppealType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="AppealType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="AppealIdentifier" type="{http://www.w3.org/2001/XMLSchema}token" minOccurs="0"/>
 *         &lt;element name="AppealDate" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/>
 *         &lt;element name="AppealDecisionDate" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/>
 *         &lt;element name="CaseReferenceDetails" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="CaseReference" type="{http://www.oami.europa.eu/TM-Search}CaseReferenceType" maxOccurs="unbounded"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="AppealDecisionStatusCode" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="AppellantDetails" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="Appellant" type="{http://www.oami.europa.eu/TM-Search}AppellantType"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="RepresentativeDetails" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="Representative" type="{http://www.oami.europa.eu/TM-Search}RepresentativeType"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "AppealType", propOrder = {
    "appealIdentifier",
    "appealDate",
    "appealDecisionDate",
    "caseReferenceDetails",
    "appealDecisionStatusCode",
    "appellantDetails",
    "representativeDetails"
})
public class AppealType {

    @XmlElement(name = "AppealIdentifier")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "token")
    protected String appealIdentifier;
    @XmlElement(name = "AppealDate")
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar appealDate;
    @XmlElement(name = "AppealDecisionDate")
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar appealDecisionDate;
    @XmlElement(name = "CaseReferenceDetails")
    protected AppealType.CaseReferenceDetails caseReferenceDetails;
    @XmlElement(name = "AppealDecisionStatusCode")
    protected String appealDecisionStatusCode;
    @XmlElement(name = "AppellantDetails")
    protected AppealType.AppellantDetails appellantDetails;
    @XmlElement(name = "RepresentativeDetails")
    protected AppealType.RepresentativeDetails representativeDetails;

    /**
     * Gets the value of the appealIdentifier property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAppealIdentifier() {
        return appealIdentifier;
    }

    /**
     * Sets the value of the appealIdentifier property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAppealIdentifier(String value) {
        this.appealIdentifier = value;
    }

    /**
     * Gets the value of the appealDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getAppealDate() {
        return appealDate;
    }

    /**
     * Sets the value of the appealDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setAppealDate(XMLGregorianCalendar value) {
        this.appealDate = value;
    }

    /**
     * Gets the value of the appealDecisionDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getAppealDecisionDate() {
        return appealDecisionDate;
    }

    /**
     * Sets the value of the appealDecisionDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setAppealDecisionDate(XMLGregorianCalendar value) {
        this.appealDecisionDate = value;
    }

    /**
     * Gets the value of the caseReferenceDetails property.
     * 
     * @return
     *     possible object is
     *     {@link AppealType.CaseReferenceDetails }
     *     
     */
    public AppealType.CaseReferenceDetails getCaseReferenceDetails() {
        return caseReferenceDetails;
    }

    /**
     * Sets the value of the caseReferenceDetails property.
     * 
     * @param value
     *     allowed object is
     *     {@link AppealType.CaseReferenceDetails }
     *     
     */
    public void setCaseReferenceDetails(AppealType.CaseReferenceDetails value) {
        this.caseReferenceDetails = value;
    }

    /**
     * Gets the value of the appealDecisionStatusCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAppealDecisionStatusCode() {
        return appealDecisionStatusCode;
    }

    /**
     * Sets the value of the appealDecisionStatusCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAppealDecisionStatusCode(String value) {
        this.appealDecisionStatusCode = value;
    }

    /**
     * Gets the value of the appellantDetails property.
     * 
     * @return
     *     possible object is
     *     {@link AppealType.AppellantDetails }
     *     
     */
    public AppealType.AppellantDetails getAppellantDetails() {
        return appellantDetails;
    }

    /**
     * Sets the value of the appellantDetails property.
     * 
     * @param value
     *     allowed object is
     *     {@link AppealType.AppellantDetails }
     *     
     */
    public void setAppellantDetails(AppealType.AppellantDetails value) {
        this.appellantDetails = value;
    }

    /**
     * Gets the value of the representativeDetails property.
     * 
     * @return
     *     possible object is
     *     {@link AppealType.RepresentativeDetails }
     *     
     */
    public AppealType.RepresentativeDetails getRepresentativeDetails() {
        return representativeDetails;
    }

    /**
     * Sets the value of the representativeDetails property.
     * 
     * @param value
     *     allowed object is
     *     {@link AppealType.RepresentativeDetails }
     *     
     */
    public void setRepresentativeDetails(AppealType.RepresentativeDetails value) {
        this.representativeDetails = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="Appellant" type="{http://www.oami.europa.eu/TM-Search}AppellantType"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "appellant"
    })
    public static class AppellantDetails {

        @XmlElement(name = "Appellant", required = true)
        protected AppellantType appellant;

        /**
         * Gets the value of the appellant property.
         * 
         * @return
         *     possible object is
         *     {@link AppellantType }
         *     
         */
        public AppellantType getAppellant() {
            return appellant;
        }

        /**
         * Sets the value of the appellant property.
         * 
         * @param value
         *     allowed object is
         *     {@link AppellantType }
         *     
         */
        public void setAppellant(AppellantType value) {
            this.appellant = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="CaseReference" type="{http://www.oami.europa.eu/TM-Search}CaseReferenceType" maxOccurs="unbounded"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "caseReference"
    })
    public static class CaseReferenceDetails {

        @XmlElement(name = "CaseReference", required = true)
        protected List<CaseReferenceType> caseReference;

        /**
         * Gets the value of the caseReference property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the caseReference property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getCaseReference().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link CaseReferenceType }
         * 
         * 
         */
        public List<CaseReferenceType> getCaseReference() {
            if (caseReference == null) {
                caseReference = new ArrayList<CaseReferenceType>();
            }
            return this.caseReference;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="Representative" type="{http://www.oami.europa.eu/TM-Search}RepresentativeType"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "representative"
    })
    public static class RepresentativeDetails {

        @XmlElement(name = "Representative", required = true)
        protected RepresentativeType representative;

        /**
         * Gets the value of the representative property.
         * 
         * @return
         *     possible object is
         *     {@link RepresentativeType }
         *     
         */
        public RepresentativeType getRepresentative() {
            return representative;
        }

        /**
         * Sets the value of the representative property.
         * 
         * @param value
         *     allowed object is
         *     {@link RepresentativeType }
         *     
         */
        public void setRepresentative(RepresentativeType value) {
            this.representative = value;
        }

    }

}
