//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.03.11 at 12:27:12 AM CET 
//


package jxml;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for AppealEventType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="AppealEventType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="AppealEventDate" type="{http://www.w3.org/2001/XMLSchema}date"/>
 *         &lt;element name="AppealEventCode" type="{http://www.oami.europa.eu/TM-Search}AppealEventCodeType"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "AppealEventType", propOrder = {
    "appealEventDate",
    "appealEventCode"
})
public class AppealEventType {

    @XmlElement(name = "AppealEventDate", required = true)
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar appealEventDate;
    @XmlElement(name = "AppealEventCode", required = true)
    @XmlSchemaType(name = "token")
    protected AppealEventCodeType appealEventCode;

    /**
     * Gets the value of the appealEventDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getAppealEventDate() {
        return appealEventDate;
    }

    /**
     * Sets the value of the appealEventDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setAppealEventDate(XMLGregorianCalendar value) {
        this.appealEventDate = value;
    }

    /**
     * Gets the value of the appealEventCode property.
     * 
     * @return
     *     possible object is
     *     {@link AppealEventCodeType }
     *     
     */
    public AppealEventCodeType getAppealEventCode() {
        return appealEventCode;
    }

    /**
     * Sets the value of the appealEventCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link AppealEventCodeType }
     *     
     */
    public void setAppealEventCode(AppealEventCodeType value) {
        this.appealEventCode = value;
    }

}
