//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.03.11 at 12:27:12 AM CET 
//


package jxml;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlList;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for ApplicantType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ApplicantType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="ApplicantIdentifier" type="{http://www.w3.org/2001/XMLSchema}token" minOccurs="0"/>
 *         &lt;element name="ApplicantNationalityCode" type="{http://www.oami.europa.eu/TM-Search}NationalityCodeType" minOccurs="0"/>
 *         &lt;element name="ApplicantLegalEntity" type="{http://www.oami.europa.eu/TM-Search}LegalEntityType" minOccurs="0"/>
 *         &lt;element name="ApplicantIncorporationCountryCode" type="{http://www.oami.europa.eu/TM-Search}ExtendedISOCountryCodeType" minOccurs="0"/>
 *         &lt;element name="ApplicantIncorporationState" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="ApplicantAddressBook" type="{http://www.oami.europa.eu/TM-Search}AddressBookType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ApplicantType", propOrder = {
    "applicantIdentifier",
    "applicantNationalityCode",
    "applicantLegalEntity",
    "applicantIncorporationCountryCode",
    "applicantIncorporationState",
    "applicantAddressBook"
})
public class ApplicantType {

    @XmlElement(name = "ApplicantIdentifier")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "token")
    protected String applicantIdentifier;
    @XmlList
    @XmlElement(name = "ApplicantNationalityCode")
    @XmlSchemaType(name = "anySimpleType")
    protected List<String> applicantNationalityCode;
    @XmlElement(name = "ApplicantLegalEntity")
    @XmlSchemaType(name = "token")
    protected LegalEntityType applicantLegalEntity;
    @XmlElement(name = "ApplicantIncorporationCountryCode")
    @XmlSchemaType(name = "anySimpleType")
    protected String applicantIncorporationCountryCode;
    @XmlElement(name = "ApplicantIncorporationState")
    protected String applicantIncorporationState;
    @XmlElement(name = "ApplicantAddressBook")
    protected AddressBookType applicantAddressBook;

    /**
     * Gets the value of the applicantIdentifier property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getApplicantIdentifier() {
        return applicantIdentifier;
    }

    /**
     * Sets the value of the applicantIdentifier property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setApplicantIdentifier(String value) {
        this.applicantIdentifier = value;
    }

    /**
     * Gets the value of the applicantNationalityCode property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the applicantNationalityCode property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getApplicantNationalityCode().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getApplicantNationalityCode() {
        if (applicantNationalityCode == null) {
            applicantNationalityCode = new ArrayList<String>();
        }
        return this.applicantNationalityCode;
    }

    /**
     * Gets the value of the applicantLegalEntity property.
     * 
     * @return
     *     possible object is
     *     {@link LegalEntityType }
     *     
     */
    public LegalEntityType getApplicantLegalEntity() {
        return applicantLegalEntity;
    }

    /**
     * Sets the value of the applicantLegalEntity property.
     * 
     * @param value
     *     allowed object is
     *     {@link LegalEntityType }
     *     
     */
    public void setApplicantLegalEntity(LegalEntityType value) {
        this.applicantLegalEntity = value;
    }

    /**
     * Gets the value of the applicantIncorporationCountryCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getApplicantIncorporationCountryCode() {
        return applicantIncorporationCountryCode;
    }

    /**
     * Sets the value of the applicantIncorporationCountryCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setApplicantIncorporationCountryCode(String value) {
        this.applicantIncorporationCountryCode = value;
    }

    /**
     * Gets the value of the applicantIncorporationState property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getApplicantIncorporationState() {
        return applicantIncorporationState;
    }

    /**
     * Sets the value of the applicantIncorporationState property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setApplicantIncorporationState(String value) {
        this.applicantIncorporationState = value;
    }

    /**
     * Gets the value of the applicantAddressBook property.
     * 
     * @return
     *     possible object is
     *     {@link AddressBookType }
     *     
     */
    public AddressBookType getApplicantAddressBook() {
        return applicantAddressBook;
    }

    /**
     * Sets the value of the applicantAddressBook property.
     * 
     * @param value
     *     allowed object is
     *     {@link AddressBookType }
     *     
     */
    public void setApplicantAddressBook(AddressBookType value) {
        this.applicantAddressBook = value;
    }

}
