//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.05.07 at 09:13:08 AM CEST 
//


package jxml;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for BasicRecordType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="BasicRecordType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="RecordIdentifier" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="RecordFilingDate" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/>
 *         &lt;element name="RecordNotificationDate" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/>
 *         &lt;element name="RecordEffectiveDate" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/>
 *         &lt;element name="BasicRecordKind" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="RecordReference" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="RecordPublicationDate" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/>
 *         &lt;element name="RecordPublicationDetails" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="RecordPublication" type="{http://www.oami.europa.eu/TM-Search}PublicationType" maxOccurs="unbounded"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="ClaimantDetails" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="Claimant" type="{http://www.oami.europa.eu/TM-Search}ClaimantType"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="RepresentativeDetails" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="Representative" type="{http://www.oami.europa.eu/TM-Search}RepresentativeType"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="RecordCurrentStatusCode" type="{http://www.oami.europa.eu/TM-Search}RecordCurrentStatusCodeType" minOccurs="0"/>
 *         &lt;element name="RecordCurrentStatusDate" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "BasicRecordType", propOrder = {
    "recordIdentifier",
    "recordFilingDate",
    "recordNotificationDate",
    "recordEffectiveDate",
    "basicRecordKind",
    "recordReference",
    "recordPublicationDate",
    "recordPublicationDetails",
    "claimantDetails",
    "representativeDetails",
    "recordCurrentStatusCode",
    "recordCurrentStatusDate"
})
public class BasicRecordType {

    @XmlElement(name = "RecordIdentifier")
    protected String recordIdentifier;
    @XmlElement(name = "RecordFilingDate")
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar recordFilingDate;
    @XmlElement(name = "RecordNotificationDate")
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar recordNotificationDate;
    @XmlElement(name = "RecordEffectiveDate")
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar recordEffectiveDate;
    @XmlElement(name = "BasicRecordKind")
    protected String basicRecordKind;
    @XmlElement(name = "RecordReference")
    protected String recordReference;
    @XmlElement(name = "RecordPublicationDate")
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar recordPublicationDate;
    @XmlElement(name = "RecordPublicationDetails")
    protected BasicRecordType.RecordPublicationDetails recordPublicationDetails;
    @XmlElement(name = "ClaimantDetails")
    protected BasicRecordType.ClaimantDetails claimantDetails;
    @XmlElement(name = "RepresentativeDetails")
    protected BasicRecordType.RepresentativeDetails representativeDetails;
    @XmlElement(name = "RecordCurrentStatusCode")
    @XmlSchemaType(name = "token")
    protected RecordCurrentStatusCodeType recordCurrentStatusCode;
    @XmlElement(name = "RecordCurrentStatusDate")
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar recordCurrentStatusDate;

    /**
     * Gets the value of the recordIdentifier property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRecordIdentifier() {
        return recordIdentifier;
    }

    /**
     * Sets the value of the recordIdentifier property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRecordIdentifier(String value) {
        this.recordIdentifier = value;
    }

    /**
     * Gets the value of the recordFilingDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getRecordFilingDate() {
        return recordFilingDate;
    }

    /**
     * Sets the value of the recordFilingDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setRecordFilingDate(XMLGregorianCalendar value) {
        this.recordFilingDate = value;
    }

    /**
     * Gets the value of the recordNotificationDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getRecordNotificationDate() {
        return recordNotificationDate;
    }

    /**
     * Sets the value of the recordNotificationDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setRecordNotificationDate(XMLGregorianCalendar value) {
        this.recordNotificationDate = value;
    }

    /**
     * Gets the value of the recordEffectiveDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getRecordEffectiveDate() {
        return recordEffectiveDate;
    }

    /**
     * Sets the value of the recordEffectiveDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setRecordEffectiveDate(XMLGregorianCalendar value) {
        this.recordEffectiveDate = value;
    }

    /**
     * Gets the value of the basicRecordKind property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBasicRecordKind() {
        return basicRecordKind;
    }

    /**
     * Sets the value of the basicRecordKind property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBasicRecordKind(String value) {
        this.basicRecordKind = value;
    }

    /**
     * Gets the value of the recordReference property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRecordReference() {
        return recordReference;
    }

    /**
     * Sets the value of the recordReference property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRecordReference(String value) {
        this.recordReference = value;
    }

    /**
     * Gets the value of the recordPublicationDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getRecordPublicationDate() {
        return recordPublicationDate;
    }

    /**
     * Sets the value of the recordPublicationDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setRecordPublicationDate(XMLGregorianCalendar value) {
        this.recordPublicationDate = value;
    }

    /**
     * Gets the value of the recordPublicationDetails property.
     * 
     * @return
     *     possible object is
     *     {@link BasicRecordType.RecordPublicationDetails }
     *     
     */
    public BasicRecordType.RecordPublicationDetails getRecordPublicationDetails() {
        return recordPublicationDetails;
    }

    /**
     * Sets the value of the recordPublicationDetails property.
     * 
     * @param value
     *     allowed object is
     *     {@link BasicRecordType.RecordPublicationDetails }
     *     
     */
    public void setRecordPublicationDetails(BasicRecordType.RecordPublicationDetails value) {
        this.recordPublicationDetails = value;
    }

    /**
     * Gets the value of the claimantDetails property.
     * 
     * @return
     *     possible object is
     *     {@link BasicRecordType.ClaimantDetails }
     *     
     */
    public BasicRecordType.ClaimantDetails getClaimantDetails() {
        return claimantDetails;
    }

    /**
     * Sets the value of the claimantDetails property.
     * 
     * @param value
     *     allowed object is
     *     {@link BasicRecordType.ClaimantDetails }
     *     
     */
    public void setClaimantDetails(BasicRecordType.ClaimantDetails value) {
        this.claimantDetails = value;
    }

    /**
     * Gets the value of the representativeDetails property.
     * 
     * @return
     *     possible object is
     *     {@link BasicRecordType.RepresentativeDetails }
     *     
     */
    public BasicRecordType.RepresentativeDetails getRepresentativeDetails() {
        return representativeDetails;
    }

    /**
     * Sets the value of the representativeDetails property.
     * 
     * @param value
     *     allowed object is
     *     {@link BasicRecordType.RepresentativeDetails }
     *     
     */
    public void setRepresentativeDetails(BasicRecordType.RepresentativeDetails value) {
        this.representativeDetails = value;
    }

    /**
     * Gets the value of the recordCurrentStatusCode property.
     * 
     * @return
     *     possible object is
     *     {@link RecordCurrentStatusCodeType }
     *     
     */
    public RecordCurrentStatusCodeType getRecordCurrentStatusCode() {
        return recordCurrentStatusCode;
    }

    /**
     * Sets the value of the recordCurrentStatusCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link RecordCurrentStatusCodeType }
     *     
     */
    public void setRecordCurrentStatusCode(RecordCurrentStatusCodeType value) {
        this.recordCurrentStatusCode = value;
    }

    /**
     * Gets the value of the recordCurrentStatusDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getRecordCurrentStatusDate() {
        return recordCurrentStatusDate;
    }

    /**
     * Sets the value of the recordCurrentStatusDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setRecordCurrentStatusDate(XMLGregorianCalendar value) {
        this.recordCurrentStatusDate = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="Claimant" type="{http://www.oami.europa.eu/TM-Search}ClaimantType"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "claimant"
    })
    public static class ClaimantDetails {

        @XmlElement(name = "Claimant", required = true)
        protected ClaimantType claimant;

        /**
         * Gets the value of the claimant property.
         * 
         * @return
         *     possible object is
         *     {@link ClaimantType }
         *     
         */
        public ClaimantType getClaimant() {
            return claimant;
        }

        /**
         * Sets the value of the claimant property.
         * 
         * @param value
         *     allowed object is
         *     {@link ClaimantType }
         *     
         */
        public void setClaimant(ClaimantType value) {
            this.claimant = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="RecordPublication" type="{http://www.oami.europa.eu/TM-Search}PublicationType" maxOccurs="unbounded"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "recordPublication"
    })
    public static class RecordPublicationDetails {

        @XmlElement(name = "RecordPublication", required = true)
        protected List<PublicationType> recordPublication;

        /**
         * Gets the value of the recordPublication property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the recordPublication property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getRecordPublication().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link PublicationType }
         * 
         * 
         */
        public List<PublicationType> getRecordPublication() {
            if (recordPublication == null) {
                recordPublication = new ArrayList<PublicationType>();
            }
            return this.recordPublication;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="Representative" type="{http://www.oami.europa.eu/TM-Search}RepresentativeType"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "representative"
    })
    public static class RepresentativeDetails {

        @XmlElement(name = "Representative", required = true)
        protected RepresentativeType representative;

        /**
         * Gets the value of the representative property.
         * 
         * @return
         *     possible object is
         *     {@link RepresentativeType }
         *     
         */
        public RepresentativeType getRepresentative() {
            return representative;
        }

        /**
         * Sets the value of the representative property.
         * 
         * @param value
         *     allowed object is
         *     {@link RepresentativeType }
         *     
         */
        public void setRepresentative(RepresentativeType value) {
            this.representative = value;
        }

    }

}
