//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.03.11 at 12:27:12 AM CET 
//


package jxml;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for CaseReferenceType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="CaseReferenceType">
 *   &lt;simpleContent>
 *     &lt;extension base="&lt;http://www.oami.europa.eu/TM-Search>TextType">
 *       &lt;attribute name="caseReferenceKind" type="{http://www.oami.europa.eu/TM-Search}CaseReferenceKindType" />
 *     &lt;/extension>
 *   &lt;/simpleContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CaseReferenceType")
public class CaseReferenceType
    extends TextType
{

    @XmlAttribute(name = "caseReferenceKind")
    protected CaseReferenceKindType caseReferenceKind;

    /**
     * Gets the value of the caseReferenceKind property.
     * 
     * @return
     *     possible object is
     *     {@link CaseReferenceKindType }
     *     
     */
    public CaseReferenceKindType getCaseReferenceKind() {
        return caseReferenceKind;
    }

    /**
     * Sets the value of the caseReferenceKind property.
     * 
     * @param value
     *     allowed object is
     *     {@link CaseReferenceKindType }
     *     
     */
    public void setCaseReferenceKind(CaseReferenceKindType value) {
        this.caseReferenceKind = value;
    }

}
