//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.03.11 at 12:27:12 AM CET 
//


package jxml;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for CaseReferenceKindType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="CaseReferenceKindType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}token">
 *     &lt;enumeration value="Trade Mark"/>
 *     &lt;enumeration value="Opposition"/>
 *     &lt;enumeration value="Mark Record"/>
 *     &lt;enumeration value="Decision"/>
 *     &lt;enumeration value="General Authorization"/>
 *     &lt;enumeration value="Current Account"/>
 *     &lt;enumeration value="Representative List"/>
 *     &lt;enumeration value="Appeal"/>
 *     &lt;enumeration value="Cancellation"/>
 *     &lt;enumeration value="Other"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "CaseReferenceKindType")
@XmlEnum
public enum CaseReferenceKindType {

    @XmlEnumValue("Trade Mark")
    TRADE_MARK("Trade Mark"),
    @XmlEnumValue("Opposition")
    OPPOSITION("Opposition"),
    @XmlEnumValue("Mark Record")
    MARK_RECORD("Mark Record"),
    @XmlEnumValue("Decision")
    DECISION("Decision"),
    @XmlEnumValue("General Authorization")
    GENERAL_AUTHORIZATION("General Authorization"),
    @XmlEnumValue("Current Account")
    CURRENT_ACCOUNT("Current Account"),
    @XmlEnumValue("Representative List")
    REPRESENTATIVE_LIST("Representative List"),
    @XmlEnumValue("Appeal")
    APPEAL("Appeal"),
    @XmlEnumValue("Cancellation")
    CANCELLATION("Cancellation"),
    @XmlEnumValue("Other")
    OTHER("Other");
    private final String value;

    CaseReferenceKindType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static CaseReferenceKindType fromValue(String v) {
        for (CaseReferenceKindType c: CaseReferenceKindType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
