//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.03.11 at 12:27:12 AM CET 
//


package jxml;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlList;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for ClaimantType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ClaimantType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="ClaimantIdentifier" type="{http://www.w3.org/2001/XMLSchema}token" minOccurs="0"/>
 *         &lt;element name="ClaimantSequenceNumber" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/>
 *         &lt;element name="ClaimantNationalityCode" type="{http://www.oami.europa.eu/TM-Search}NationalityCodeType" minOccurs="0"/>
 *         &lt;element name="ClaimantLegalEntity" type="{http://www.oami.europa.eu/TM-Search}LegalEntityType" minOccurs="0"/>
 *         &lt;element name="ClaimantIncorporationCountryCode" type="{http://www.oami.europa.eu/TM-Search}ExtendedISOCountryCodeType" minOccurs="0"/>
 *         &lt;element name="ClaimantIncorporationState" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="ClaimantAddressBook" type="{http://www.oami.europa.eu/TM-Search}AddressBookType" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="operationCode" type="{http://www.oami.europa.eu/TM-Search}OperationCodeType" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ClaimantType", propOrder = {
    "claimantIdentifier",
    "claimantSequenceNumber",
    "claimantNationalityCode",
    "claimantLegalEntity",
    "claimantIncorporationCountryCode",
    "claimantIncorporationState",
    "claimantAddressBook"
})
public class ClaimantType {

    @XmlElement(name = "ClaimantIdentifier")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "token")
    protected String claimantIdentifier;
    @XmlElement(name = "ClaimantSequenceNumber")
    protected BigInteger claimantSequenceNumber;
    @XmlList
    @XmlElement(name = "ClaimantNationalityCode")
    @XmlSchemaType(name = "anySimpleType")
    protected List<String> claimantNationalityCode;
    @XmlElement(name = "ClaimantLegalEntity")
    @XmlSchemaType(name = "token")
    protected LegalEntityType claimantLegalEntity;
    @XmlElement(name = "ClaimantIncorporationCountryCode")
    @XmlSchemaType(name = "anySimpleType")
    protected String claimantIncorporationCountryCode;
    @XmlElement(name = "ClaimantIncorporationState")
    protected String claimantIncorporationState;
    @XmlElement(name = "ClaimantAddressBook")
    protected AddressBookType claimantAddressBook;
    @XmlAttribute(name = "operationCode")
    protected OperationCodeType operationCode;

    /**
     * Gets the value of the claimantIdentifier property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getClaimantIdentifier() {
        return claimantIdentifier;
    }

    /**
     * Sets the value of the claimantIdentifier property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setClaimantIdentifier(String value) {
        this.claimantIdentifier = value;
    }

    /**
     * Gets the value of the claimantSequenceNumber property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getClaimantSequenceNumber() {
        return claimantSequenceNumber;
    }

    /**
     * Sets the value of the claimantSequenceNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setClaimantSequenceNumber(BigInteger value) {
        this.claimantSequenceNumber = value;
    }

    /**
     * Gets the value of the claimantNationalityCode property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the claimantNationalityCode property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getClaimantNationalityCode().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getClaimantNationalityCode() {
        if (claimantNationalityCode == null) {
            claimantNationalityCode = new ArrayList<String>();
        }
        return this.claimantNationalityCode;
    }

    /**
     * Gets the value of the claimantLegalEntity property.
     * 
     * @return
     *     possible object is
     *     {@link LegalEntityType }
     *     
     */
    public LegalEntityType getClaimantLegalEntity() {
        return claimantLegalEntity;
    }

    /**
     * Sets the value of the claimantLegalEntity property.
     * 
     * @param value
     *     allowed object is
     *     {@link LegalEntityType }
     *     
     */
    public void setClaimantLegalEntity(LegalEntityType value) {
        this.claimantLegalEntity = value;
    }

    /**
     * Gets the value of the claimantIncorporationCountryCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getClaimantIncorporationCountryCode() {
        return claimantIncorporationCountryCode;
    }

    /**
     * Sets the value of the claimantIncorporationCountryCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setClaimantIncorporationCountryCode(String value) {
        this.claimantIncorporationCountryCode = value;
    }

    /**
     * Gets the value of the claimantIncorporationState property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getClaimantIncorporationState() {
        return claimantIncorporationState;
    }

    /**
     * Sets the value of the claimantIncorporationState property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setClaimantIncorporationState(String value) {
        this.claimantIncorporationState = value;
    }

    /**
     * Gets the value of the claimantAddressBook property.
     * 
     * @return
     *     possible object is
     *     {@link AddressBookType }
     *     
     */
    public AddressBookType getClaimantAddressBook() {
        return claimantAddressBook;
    }

    /**
     * Sets the value of the claimantAddressBook property.
     * 
     * @param value
     *     allowed object is
     *     {@link AddressBookType }
     *     
     */
    public void setClaimantAddressBook(AddressBookType value) {
        this.claimantAddressBook = value;
    }

    /**
     * Gets the value of the operationCode property.
     * 
     * @return
     *     possible object is
     *     {@link OperationCodeType }
     *     
     */
    public OperationCodeType getOperationCode() {
        return operationCode;
    }

    /**
     * Sets the value of the operationCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link OperationCodeType }
     *     
     */
    public void setOperationCode(OperationCodeType value) {
        this.operationCode = value;
    }

}
