//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.03.11 at 12:27:12 AM CET 
//


package jxml;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ClassDescriptionType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ClassDescriptionType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="ClassNumber" type="{http://www.oami.europa.eu/TM-Search}ClassNumberType" minOccurs="0"/>
 *         &lt;element name="ClassNumberStatusCode" type="{http://www.oami.europa.eu/TM-Search}ClassNumberStatusCodeType" minOccurs="0"/>
 *         &lt;element name="GoodsServicesDescription" type="{http://www.oami.europa.eu/TM-Search}TextType" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ClassDescriptionType", propOrder = {
    "classNumber",
    "classNumberStatusCode",
    "goodsServicesDescription"
})
public class ClassDescriptionType {

    @XmlElement(name = "ClassNumber")
    @XmlSchemaType(name = "anySimpleType")
    protected String classNumber;
    @XmlElement(name = "ClassNumberStatusCode")
    @XmlSchemaType(name = "token")
    protected ClassNumberStatusCodeType classNumberStatusCode;
    @XmlElement(name = "GoodsServicesDescription")
    protected List<TextType> goodsServicesDescription;

    /**
     * Gets the value of the classNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getClassNumber() {
        return classNumber;
    }

    /**
     * Sets the value of the classNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setClassNumber(String value) {
        this.classNumber = value;
    }

    /**
     * Gets the value of the classNumberStatusCode property.
     * 
     * @return
     *     possible object is
     *     {@link ClassNumberStatusCodeType }
     *     
     */
    public ClassNumberStatusCodeType getClassNumberStatusCode() {
        return classNumberStatusCode;
    }

    /**
     * Sets the value of the classNumberStatusCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link ClassNumberStatusCodeType }
     *     
     */
    public void setClassNumberStatusCode(ClassNumberStatusCodeType value) {
        this.classNumberStatusCode = value;
    }

    /**
     * Gets the value of the goodsServicesDescription property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the goodsServicesDescription property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getGoodsServicesDescription().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TextType }
     * 
     * 
     */
    public List<TextType> getGoodsServicesDescription() {
        if (goodsServicesDescription == null) {
            goodsServicesDescription = new ArrayList<TextType>();
        }
        return this.goodsServicesDescription;
    }

}
