//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.03.11 at 12:27:12 AM CET 
//


package jxml;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for EarlierMarkType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="EarlierMarkType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="EarlierMarkCountryCode" type="{http://www.oami.europa.eu/TM-Search}WIPOST3CodeType" minOccurs="0"/>
 *         &lt;element name="DesignatedCountryDetails" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="DesignatedCountry" type="{http://www.oami.europa.eu/TM-Search}DesignatedCountryType" maxOccurs="unbounded"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="ApplicationNumber" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="ApplicationDate" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/>
 *         &lt;element name="RegistrationNumber" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="RegistrationDate" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/>
 *         &lt;element name="MarkFeature" type="{http://www.oami.europa.eu/TM-Search}MarkFeatureType" minOccurs="0"/>
 *         &lt;element name="WordMarkSpecification" type="{http://www.oami.europa.eu/TM-Search}WordMarkSpecificationType" minOccurs="0"/>
 *         &lt;element name="OppositionBasisCode" type="{http://www.oami.europa.eu/TM-Search}OppositionBasisCodeType" minOccurs="0"/>
 *         &lt;element name="OppositionGroundTextDetails" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="OppositionGroundText" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "EarlierMarkType", propOrder = {
    "earlierMarkCountryCode",
    "designatedCountryDetails",
    "applicationNumber",
    "applicationDate",
    "registrationNumber",
    "registrationDate",
    "markFeature",
    "wordMarkSpecification",
    "oppositionBasisCode",
    "oppositionGroundTextDetails"
})
public class EarlierMarkType {

    @XmlElement(name = "EarlierMarkCountryCode")
    @XmlSchemaType(name = "NMTOKEN")
    protected WIPOST3CodeType earlierMarkCountryCode;
    @XmlElement(name = "DesignatedCountryDetails")
    protected EarlierMarkType.DesignatedCountryDetails designatedCountryDetails;
    @XmlElement(name = "ApplicationNumber")
    protected String applicationNumber;
    @XmlElement(name = "ApplicationDate")
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar applicationDate;
    @XmlElement(name = "RegistrationNumber")
    protected String registrationNumber;
    @XmlElement(name = "RegistrationDate")
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar registrationDate;
    @XmlElement(name = "MarkFeature")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "token")
    protected String markFeature;
    @XmlElement(name = "WordMarkSpecification")
    protected WordMarkSpecificationType wordMarkSpecification;
    @XmlElement(name = "OppositionBasisCode")
    @XmlSchemaType(name = "token")
    protected OppositionBasisCodeType oppositionBasisCode;
    @XmlElement(name = "OppositionGroundTextDetails")
    protected EarlierMarkType.OppositionGroundTextDetails oppositionGroundTextDetails;

    /**
     * Gets the value of the earlierMarkCountryCode property.
     * 
     * @return
     *     possible object is
     *     {@link WIPOST3CodeType }
     *     
     */
    public WIPOST3CodeType getEarlierMarkCountryCode() {
        return earlierMarkCountryCode;
    }

    /**
     * Sets the value of the earlierMarkCountryCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link WIPOST3CodeType }
     *     
     */
    public void setEarlierMarkCountryCode(WIPOST3CodeType value) {
        this.earlierMarkCountryCode = value;
    }

    /**
     * Gets the value of the designatedCountryDetails property.
     * 
     * @return
     *     possible object is
     *     {@link EarlierMarkType.DesignatedCountryDetails }
     *     
     */
    public EarlierMarkType.DesignatedCountryDetails getDesignatedCountryDetails() {
        return designatedCountryDetails;
    }

    /**
     * Sets the value of the designatedCountryDetails property.
     * 
     * @param value
     *     allowed object is
     *     {@link EarlierMarkType.DesignatedCountryDetails }
     *     
     */
    public void setDesignatedCountryDetails(EarlierMarkType.DesignatedCountryDetails value) {
        this.designatedCountryDetails = value;
    }

    /**
     * Gets the value of the applicationNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getApplicationNumber() {
        return applicationNumber;
    }

    /**
     * Sets the value of the applicationNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setApplicationNumber(String value) {
        this.applicationNumber = value;
    }

    /**
     * Gets the value of the applicationDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getApplicationDate() {
        return applicationDate;
    }

    /**
     * Sets the value of the applicationDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setApplicationDate(XMLGregorianCalendar value) {
        this.applicationDate = value;
    }

    /**
     * Gets the value of the registrationNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRegistrationNumber() {
        return registrationNumber;
    }

    /**
     * Sets the value of the registrationNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRegistrationNumber(String value) {
        this.registrationNumber = value;
    }

    /**
     * Gets the value of the registrationDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getRegistrationDate() {
        return registrationDate;
    }

    /**
     * Sets the value of the registrationDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setRegistrationDate(XMLGregorianCalendar value) {
        this.registrationDate = value;
    }

    /**
     * Gets the value of the markFeature property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMarkFeature() {
        return markFeature;
    }

    /**
     * Sets the value of the markFeature property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMarkFeature(String value) {
        this.markFeature = value;
    }

    /**
     * Gets the value of the wordMarkSpecification property.
     * 
     * @return
     *     possible object is
     *     {@link WordMarkSpecificationType }
     *     
     */
    public WordMarkSpecificationType getWordMarkSpecification() {
        return wordMarkSpecification;
    }

    /**
     * Sets the value of the wordMarkSpecification property.
     * 
     * @param value
     *     allowed object is
     *     {@link WordMarkSpecificationType }
     *     
     */
    public void setWordMarkSpecification(WordMarkSpecificationType value) {
        this.wordMarkSpecification = value;
    }

    /**
     * Gets the value of the oppositionBasisCode property.
     * 
     * @return
     *     possible object is
     *     {@link OppositionBasisCodeType }
     *     
     */
    public OppositionBasisCodeType getOppositionBasisCode() {
        return oppositionBasisCode;
    }

    /**
     * Sets the value of the oppositionBasisCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link OppositionBasisCodeType }
     *     
     */
    public void setOppositionBasisCode(OppositionBasisCodeType value) {
        this.oppositionBasisCode = value;
    }

    /**
     * Gets the value of the oppositionGroundTextDetails property.
     * 
     * @return
     *     possible object is
     *     {@link EarlierMarkType.OppositionGroundTextDetails }
     *     
     */
    public EarlierMarkType.OppositionGroundTextDetails getOppositionGroundTextDetails() {
        return oppositionGroundTextDetails;
    }

    /**
     * Sets the value of the oppositionGroundTextDetails property.
     * 
     * @param value
     *     allowed object is
     *     {@link EarlierMarkType.OppositionGroundTextDetails }
     *     
     */
    public void setOppositionGroundTextDetails(EarlierMarkType.OppositionGroundTextDetails value) {
        this.oppositionGroundTextDetails = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="DesignatedCountry" type="{http://www.oami.europa.eu/TM-Search}DesignatedCountryType" maxOccurs="unbounded"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "designatedCountry"
    })
    public static class DesignatedCountryDetails {

        @XmlElement(name = "DesignatedCountry", required = true)
        protected List<DesignatedCountryType> designatedCountry;

        /**
         * Gets the value of the designatedCountry property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the designatedCountry property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getDesignatedCountry().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link DesignatedCountryType }
         * 
         * 
         */
        public List<DesignatedCountryType> getDesignatedCountry() {
            if (designatedCountry == null) {
                designatedCountry = new ArrayList<DesignatedCountryType>();
            }
            return this.designatedCountry;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="OppositionGroundText" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "oppositionGroundText"
    })
    public static class OppositionGroundTextDetails {

        @XmlElement(name = "OppositionGroundText", required = true)
        protected List<String> oppositionGroundText;

        /**
         * Gets the value of the oppositionGroundText property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the oppositionGroundText property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getOppositionGroundText().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link String }
         * 
         * 
         */
        public List<String> getOppositionGroundText() {
            if (oppositionGroundText == null) {
                oppositionGroundText = new ArrayList<String>();
            }
            return this.oppositionGroundText;
        }

    }

}
