//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.03.11 at 12:27:12 AM CET 
//


package jxml;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for FreeFormatNameType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="FreeFormatNameType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="FreeFormatNameDetails" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="FreeFormatNameLine" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "FreeFormatNameType", propOrder = {
    "freeFormatNameDetails"
})
public class FreeFormatNameType {

    @XmlElement(name = "FreeFormatNameDetails")
    protected FreeFormatNameType.FreeFormatNameDetails freeFormatNameDetails;

    /**
     * Gets the value of the freeFormatNameDetails property.
     * 
     * @return
     *     possible object is
     *     {@link FreeFormatNameType.FreeFormatNameDetails }
     *     
     */
    public FreeFormatNameType.FreeFormatNameDetails getFreeFormatNameDetails() {
        return freeFormatNameDetails;
    }

    /**
     * Sets the value of the freeFormatNameDetails property.
     * 
     * @param value
     *     allowed object is
     *     {@link FreeFormatNameType.FreeFormatNameDetails }
     *     
     */
    public void setFreeFormatNameDetails(FreeFormatNameType.FreeFormatNameDetails value) {
        this.freeFormatNameDetails = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="FreeFormatNameLine" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "freeFormatNameLine"
    })
    public static class FreeFormatNameDetails {

        @XmlElement(name = "FreeFormatNameLine", required = true)
        protected List<String> freeFormatNameLine;

        /**
         * Gets the value of the freeFormatNameLine property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the freeFormatNameLine property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getFreeFormatNameLine().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link String }
         * 
         * 
         */
        public List<String> getFreeFormatNameLine() {
            if (freeFormatNameLine == null) {
                freeFormatNameLine = new ArrayList<String>();
            }
            return this.freeFormatNameLine;
        }

    }

}
