//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.03.11 at 12:27:12 AM CET 
//


package jxml;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for GoodsServicesType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="GoodsServicesType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="ClassificationKindCode" type="{http://www.oami.europa.eu/TM-Search}ClassificationKindCodeType" minOccurs="0"/>
 *         &lt;element name="ClassificationVersion" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="ClassDescriptionDetails">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="ClassDescription" type="{http://www.oami.europa.eu/TM-Search}ClassDescriptionType" maxOccurs="unbounded"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "GoodsServicesType", propOrder = {
    "classificationKindCode",
    "classificationVersion",
    "classDescriptionDetails"
})
public class GoodsServicesType {

    @XmlElement(name = "ClassificationKindCode")
    @XmlSchemaType(name = "token")
    protected ClassificationKindCodeType classificationKindCode;
    @XmlElement(name = "ClassificationVersion")
    protected String classificationVersion;
    @XmlElement(name = "ClassDescriptionDetails", required = true)
    protected GoodsServicesType.ClassDescriptionDetails classDescriptionDetails;

    /**
     * Gets the value of the classificationKindCode property.
     * 
     * @return
     *     possible object is
     *     {@link ClassificationKindCodeType }
     *     
     */
    public ClassificationKindCodeType getClassificationKindCode() {
        return classificationKindCode;
    }

    /**
     * Sets the value of the classificationKindCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link ClassificationKindCodeType }
     *     
     */
    public void setClassificationKindCode(ClassificationKindCodeType value) {
        this.classificationKindCode = value;
    }

    /**
     * Gets the value of the classificationVersion property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getClassificationVersion() {
        return classificationVersion;
    }

    /**
     * Sets the value of the classificationVersion property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setClassificationVersion(String value) {
        this.classificationVersion = value;
    }

    /**
     * Gets the value of the classDescriptionDetails property.
     * 
     * @return
     *     possible object is
     *     {@link GoodsServicesType.ClassDescriptionDetails }
     *     
     */
    public GoodsServicesType.ClassDescriptionDetails getClassDescriptionDetails() {
        return classDescriptionDetails;
    }

    /**
     * Sets the value of the classDescriptionDetails property.
     * 
     * @param value
     *     allowed object is
     *     {@link GoodsServicesType.ClassDescriptionDetails }
     *     
     */
    public void setClassDescriptionDetails(GoodsServicesType.ClassDescriptionDetails value) {
        this.classDescriptionDetails = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="ClassDescription" type="{http://www.oami.europa.eu/TM-Search}ClassDescriptionType" maxOccurs="unbounded"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "classDescription"
    })
    public static class ClassDescriptionDetails {

        @XmlElement(name = "ClassDescription", required = true)
        protected List<ClassDescriptionType> classDescription;

        /**
         * Gets the value of the classDescription property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the classDescription property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getClassDescription().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link ClassDescriptionType }
         * 
         * 
         */
        public List<ClassDescriptionType> getClassDescription() {
            if (classDescription == null) {
                classDescription = new ArrayList<ClassDescriptionType>();
            }
            return this.classDescription;
        }

    }

}
