//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.03.11 at 12:27:12 AM CET 
//


package jxml;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ISOLanguageCodeType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="ISOLanguageCodeType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}NMTOKEN">
 *     &lt;enumeration value="aa"/>
 *     &lt;enumeration value="ab"/>
 *     &lt;enumeration value="af"/>
 *     &lt;enumeration value="am"/>
 *     &lt;enumeration value="ar"/>
 *     &lt;enumeration value="as"/>
 *     &lt;enumeration value="ay"/>
 *     &lt;enumeration value="az"/>
 *     &lt;enumeration value="ba"/>
 *     &lt;enumeration value="be"/>
 *     &lt;enumeration value="bg"/>
 *     &lt;enumeration value="bh"/>
 *     &lt;enumeration value="bi"/>
 *     &lt;enumeration value="bn"/>
 *     &lt;enumeration value="bo"/>
 *     &lt;enumeration value="br"/>
 *     &lt;enumeration value="ca"/>
 *     &lt;enumeration value="co"/>
 *     &lt;enumeration value="cs"/>
 *     &lt;enumeration value="cy"/>
 *     &lt;enumeration value="da"/>
 *     &lt;enumeration value="de"/>
 *     &lt;enumeration value="dz"/>
 *     &lt;enumeration value="el"/>
 *     &lt;enumeration value="en"/>
 *     &lt;enumeration value="eo"/>
 *     &lt;enumeration value="es"/>
 *     &lt;enumeration value="et"/>
 *     &lt;enumeration value="eu"/>
 *     &lt;enumeration value="fa"/>
 *     &lt;enumeration value="fi"/>
 *     &lt;enumeration value="fj"/>
 *     &lt;enumeration value="fo"/>
 *     &lt;enumeration value="fr"/>
 *     &lt;enumeration value="fy"/>
 *     &lt;enumeration value="ga"/>
 *     &lt;enumeration value="gd"/>
 *     &lt;enumeration value="gl"/>
 *     &lt;enumeration value="gn"/>
 *     &lt;enumeration value="gu"/>
 *     &lt;enumeration value="ha"/>
 *     &lt;enumeration value="he"/>
 *     &lt;enumeration value="hi"/>
 *     &lt;enumeration value="hr"/>
 *     &lt;enumeration value="hu"/>
 *     &lt;enumeration value="hy"/>
 *     &lt;enumeration value="ia"/>
 *     &lt;enumeration value="id"/>
 *     &lt;enumeration value="ie"/>
 *     &lt;enumeration value="ik"/>
 *     &lt;enumeration value="is"/>
 *     &lt;enumeration value="it"/>
 *     &lt;enumeration value="iu"/>
 *     &lt;enumeration value="ja"/>
 *     &lt;enumeration value="jw"/>
 *     &lt;enumeration value="ka"/>
 *     &lt;enumeration value="kk"/>
 *     &lt;enumeration value="kl"/>
 *     &lt;enumeration value="km"/>
 *     &lt;enumeration value="kn"/>
 *     &lt;enumeration value="ko"/>
 *     &lt;enumeration value="ks"/>
 *     &lt;enumeration value="ku"/>
 *     &lt;enumeration value="ky"/>
 *     &lt;enumeration value="la"/>
 *     &lt;enumeration value="ln"/>
 *     &lt;enumeration value="lo"/>
 *     &lt;enumeration value="lt"/>
 *     &lt;enumeration value="lv"/>
 *     &lt;enumeration value="mg"/>
 *     &lt;enumeration value="mi"/>
 *     &lt;enumeration value="mk"/>
 *     &lt;enumeration value="ml"/>
 *     &lt;enumeration value="mn"/>
 *     &lt;enumeration value="mo"/>
 *     &lt;enumeration value="mr"/>
 *     &lt;enumeration value="ms"/>
 *     &lt;enumeration value="mt"/>
 *     &lt;enumeration value="my"/>
 *     &lt;enumeration value="na"/>
 *     &lt;enumeration value="ne"/>
 *     &lt;enumeration value="nl"/>
 *     &lt;enumeration value="no"/>
 *     &lt;enumeration value="oc"/>
 *     &lt;enumeration value="om"/>
 *     &lt;enumeration value="or"/>
 *     &lt;enumeration value="pa"/>
 *     &lt;enumeration value="pl"/>
 *     &lt;enumeration value="ps"/>
 *     &lt;enumeration value="pt"/>
 *     &lt;enumeration value="qu"/>
 *     &lt;enumeration value="rm"/>
 *     &lt;enumeration value="rn"/>
 *     &lt;enumeration value="ro"/>
 *     &lt;enumeration value="ru"/>
 *     &lt;enumeration value="rw"/>
 *     &lt;enumeration value="sa"/>
 *     &lt;enumeration value="sd"/>
 *     &lt;enumeration value="sg"/>
 *     &lt;enumeration value="sh"/>
 *     &lt;enumeration value="si"/>
 *     &lt;enumeration value="sk"/>
 *     &lt;enumeration value="sl"/>
 *     &lt;enumeration value="sm"/>
 *     &lt;enumeration value="sn"/>
 *     &lt;enumeration value="so"/>
 *     &lt;enumeration value="sq"/>
 *     &lt;enumeration value="sr"/>
 *     &lt;enumeration value="ss"/>
 *     &lt;enumeration value="st"/>
 *     &lt;enumeration value="su"/>
 *     &lt;enumeration value="sv"/>
 *     &lt;enumeration value="sw"/>
 *     &lt;enumeration value="ta"/>
 *     &lt;enumeration value="te"/>
 *     &lt;enumeration value="tg"/>
 *     &lt;enumeration value="th"/>
 *     &lt;enumeration value="ti"/>
 *     &lt;enumeration value="tk"/>
 *     &lt;enumeration value="tl"/>
 *     &lt;enumeration value="tn"/>
 *     &lt;enumeration value="to"/>
 *     &lt;enumeration value="tr"/>
 *     &lt;enumeration value="ts"/>
 *     &lt;enumeration value="tt"/>
 *     &lt;enumeration value="tw"/>
 *     &lt;enumeration value="ug"/>
 *     &lt;enumeration value="uk"/>
 *     &lt;enumeration value="ur"/>
 *     &lt;enumeration value="uz"/>
 *     &lt;enumeration value="vi"/>
 *     &lt;enumeration value="vo"/>
 *     &lt;enumeration value="wo"/>
 *     &lt;enumeration value="xh"/>
 *     &lt;enumeration value="yi"/>
 *     &lt;enumeration value="yo"/>
 *     &lt;enumeration value="za"/>
 *     &lt;enumeration value="zh"/>
 *     &lt;enumeration value="zu"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "ISOLanguageCodeType")
@XmlEnum
public enum ISOLanguageCodeType {


    /**
     * Afar
     * 
     */
    @XmlEnumValue("aa")
    AA("aa"),

    /**
     * Abkhazian
     * 
     */
    @XmlEnumValue("ab")
    AB("ab"),

    /**
     * Afrikaans
     * 
     */
    @XmlEnumValue("af")
    AF("af"),

    /**
     * Amharic
     * 
     */
    @XmlEnumValue("am")
    AM("am"),

    /**
     * Arabic
     * 
     */
    @XmlEnumValue("ar")
    AR("ar"),

    /**
     * Assamese
     * 
     */
    @XmlEnumValue("as")
    AS("as"),

    /**
     * Aymara
     * 
     */
    @XmlEnumValue("ay")
    AY("ay"),

    /**
     * Azerbaijani
     * 
     */
    @XmlEnumValue("az")
    AZ("az"),

    /**
     * Bashkir
     * 
     */
    @XmlEnumValue("ba")
    BA("ba"),

    /**
     * Byelorussian
     * 
     */
    @XmlEnumValue("be")
    BE("be"),

    /**
     * Bulgarian
     * 
     */
    @XmlEnumValue("bg")
    BG("bg"),

    /**
     * Bihari
     * 
     */
    @XmlEnumValue("bh")
    BH("bh"),

    /**
     * Bislama
     * 
     */
    @XmlEnumValue("bi")
    BI("bi"),

    /**
     * Bengali; Bangla
     * 
     */
    @XmlEnumValue("bn")
    BN("bn"),

    /**
     * Tibetan
     * 
     */
    @XmlEnumValue("bo")
    BO("bo"),

    /**
     * Breton
     * 
     */
    @XmlEnumValue("br")
    BR("br"),

    /**
     * Catalan
     * 
     */
    @XmlEnumValue("ca")
    CA("ca"),

    /**
     * Corsican
     * 
     */
    @XmlEnumValue("co")
    CO("co"),

    /**
     * Czech
     * 
     */
    @XmlEnumValue("cs")
    CS("cs"),

    /**
     * Welsh
     * 
     */
    @XmlEnumValue("cy")
    CY("cy"),

    /**
     * Danish
     * 
     */
    @XmlEnumValue("da")
    DA("da"),

    /**
     * German
     * 
     */
    @XmlEnumValue("de")
    DE("de"),

    /**
     * Bhutani
     * 
     */
    @XmlEnumValue("dz")
    DZ("dz"),

    /**
     * Greek
     * 
     */
    @XmlEnumValue("el")
    EL("el"),

    /**
     * English
     * 
     */
    @XmlEnumValue("en")
    EN("en"),

    /**
     * Esperanto
     * 
     */
    @XmlEnumValue("eo")
    EO("eo"),

    /**
     * Spanish
     * 
     */
    @XmlEnumValue("es")
    ES("es"),

    /**
     * Estonian
     * 
     */
    @XmlEnumValue("et")
    ET("et"),

    /**
     * Basque
     * 
     */
    @XmlEnumValue("eu")
    EU("eu"),

    /**
     * Persian
     * 
     */
    @XmlEnumValue("fa")
    FA("fa"),

    /**
     * Finnish
     * 
     */
    @XmlEnumValue("fi")
    FI("fi"),

    /**
     * Fiji
     * 
     */
    @XmlEnumValue("fj")
    FJ("fj"),

    /**
     * Faroese
     * 
     */
    @XmlEnumValue("fo")
    FO("fo"),

    /**
     * French
     * 
     */
    @XmlEnumValue("fr")
    FR("fr"),

    /**
     * Frisian
     * 
     */
    @XmlEnumValue("fy")
    FY("fy"),

    /**
     * Irish
     * 
     */
    @XmlEnumValue("ga")
    GA("ga"),

    /**
     * Scots Gaelic
     * 
     */
    @XmlEnumValue("gd")
    GD("gd"),

    /**
     * Galician
     * 
     */
    @XmlEnumValue("gl")
    GL("gl"),

    /**
     * Guarani
     * 
     */
    @XmlEnumValue("gn")
    GN("gn"),

    /**
     * Gujarati
     * 
     */
    @XmlEnumValue("gu")
    GU("gu"),

    /**
     * Hausa
     * 
     */
    @XmlEnumValue("ha")
    HA("ha"),

    /**
     * Hebrew
     * 
     */
    @XmlEnumValue("he")
    HE("he"),

    /**
     * Hindi
     * 
     */
    @XmlEnumValue("hi")
    HI("hi"),

    /**
     * Croatian
     * 
     */
    @XmlEnumValue("hr")
    HR("hr"),

    /**
     * Hungarian
     * 
     */
    @XmlEnumValue("hu")
    HU("hu"),

    /**
     * Armenian
     * 
     */
    @XmlEnumValue("hy")
    HY("hy"),

    /**
     * Interlingua
     * 
     */
    @XmlEnumValue("ia")
    IA("ia"),

    /**
     * Indonesian
     * 
     */
    @XmlEnumValue("id")
    ID("id"),

    /**
     * Interlingue
     * 
     */
    @XmlEnumValue("ie")
    IE("ie"),

    /**
     * Inupiak
     * 
     */
    @XmlEnumValue("ik")
    IK("ik"),

    /**
     * Icelandic
     * 
     */
    @XmlEnumValue("is")
    IS("is"),

    /**
     * Italian
     * 
     */
    @XmlEnumValue("it")
    IT("it"),

    /**
     * Inuktitut
     * 
     */
    @XmlEnumValue("iu")
    IU("iu"),

    /**
     * Japanese
     * 
     */
    @XmlEnumValue("ja")
    JA("ja"),

    /**
     * Javanese
     * 
     */
    @XmlEnumValue("jw")
    JW("jw"),

    /**
     * Georgian
     * 
     */
    @XmlEnumValue("ka")
    KA("ka"),

    /**
     * Kazakh
     * 
     */
    @XmlEnumValue("kk")
    KK("kk"),

    /**
     * Greenlandic
     * 
     */
    @XmlEnumValue("kl")
    KL("kl"),

    /**
     * Cambodian
     * 
     */
    @XmlEnumValue("km")
    KM("km"),

    /**
     * Kannada
     * 
     */
    @XmlEnumValue("kn")
    KN("kn"),

    /**
     * Korean
     * 
     */
    @XmlEnumValue("ko")
    KO("ko"),

    /**
     * Kashmiri
     * 
     */
    @XmlEnumValue("ks")
    KS("ks"),

    /**
     * Kurdish
     * 
     */
    @XmlEnumValue("ku")
    KU("ku"),

    /**
     * Kirghiz
     * 
     */
    @XmlEnumValue("ky")
    KY("ky"),

    /**
     * Latin
     * 
     */
    @XmlEnumValue("la")
    LA("la"),

    /**
     * Lingala
     * 
     */
    @XmlEnumValue("ln")
    LN("ln"),

    /**
     * Laothian
     * 
     */
    @XmlEnumValue("lo")
    LO("lo"),

    /**
     * Lithuanian
     * 
     */
    @XmlEnumValue("lt")
    LT("lt"),

    /**
     * Latvian; Lettish
     * 
     */
    @XmlEnumValue("lv")
    LV("lv"),

    /**
     * Malagasy
     * 
     */
    @XmlEnumValue("mg")
    MG("mg"),

    /**
     * Maori
     * 
     */
    @XmlEnumValue("mi")
    MI("mi"),

    /**
     * Macedonian
     * 
     */
    @XmlEnumValue("mk")
    MK("mk"),

    /**
     * Malayalam
     * 
     */
    @XmlEnumValue("ml")
    ML("ml"),

    /**
     * Mongolian
     * 
     */
    @XmlEnumValue("mn")
    MN("mn"),

    /**
     * Moldavian
     * 
     */
    @XmlEnumValue("mo")
    MO("mo"),

    /**
     * Marathi
     * 
     */
    @XmlEnumValue("mr")
    MR("mr"),

    /**
     * Malay
     * 
     */
    @XmlEnumValue("ms")
    MS("ms"),

    /**
     * Maltese
     * 
     */
    @XmlEnumValue("mt")
    MT("mt"),

    /**
     * Burmese
     * 
     */
    @XmlEnumValue("my")
    MY("my"),

    /**
     * Nauru
     * 
     */
    @XmlEnumValue("na")
    NA("na"),

    /**
     * Nepali
     * 
     */
    @XmlEnumValue("ne")
    NE("ne"),

    /**
     * Dutch
     * 
     */
    @XmlEnumValue("nl")
    NL("nl"),

    /**
     * Norwegian
     * 
     */
    @XmlEnumValue("no")
    NO("no"),

    /**
     * Occitan
     * 
     */
    @XmlEnumValue("oc")
    OC("oc"),

    /**
     * (Afan) Oromo
     * 
     */
    @XmlEnumValue("om")
    OM("om"),

    /**
     * Oriya
     * 
     */
    @XmlEnumValue("or")
    OR("or"),

    /**
     * Punjabi
     * 
     */
    @XmlEnumValue("pa")
    PA("pa"),

    /**
     * Polish
     * 
     */
    @XmlEnumValue("pl")
    PL("pl"),

    /**
     * Pashto, Pushto
     * 
     */
    @XmlEnumValue("ps")
    PS("ps"),

    /**
     * Portuguese
     * 
     */
    @XmlEnumValue("pt")
    PT("pt"),

    /**
     * Quechua
     * 
     */
    @XmlEnumValue("qu")
    QU("qu"),

    /**
     * Rhaeto-Romance
     * 
     */
    @XmlEnumValue("rm")
    RM("rm"),

    /**
     * Kirundi
     * 
     */
    @XmlEnumValue("rn")
    RN("rn"),

    /**
     * Romanian
     * 
     */
    @XmlEnumValue("ro")
    RO("ro"),

    /**
     * Russian
     * 
     */
    @XmlEnumValue("ru")
    RU("ru"),

    /**
     * Kinyarwanda
     * 
     */
    @XmlEnumValue("rw")
    RW("rw"),

    /**
     * Sanskrit
     * 
     */
    @XmlEnumValue("sa")
    SA("sa"),

    /**
     * Sindhi
     * 
     */
    @XmlEnumValue("sd")
    SD("sd"),

    /**
     * Sangho
     * 
     */
    @XmlEnumValue("sg")
    SG("sg"),

    /**
     * Serbo-Croatian
     * 
     */
    @XmlEnumValue("sh")
    SH("sh"),

    /**
     * Singhalese
     * 
     */
    @XmlEnumValue("si")
    SI("si"),

    /**
     * Slovak
     * 
     */
    @XmlEnumValue("sk")
    SK("sk"),

    /**
     * Slovenian
     * 
     */
    @XmlEnumValue("sl")
    SL("sl"),

    /**
     * Samoan
     * 
     */
    @XmlEnumValue("sm")
    SM("sm"),

    /**
     * Shona
     * 
     */
    @XmlEnumValue("sn")
    SN("sn"),

    /**
     * Somali
     * 
     */
    @XmlEnumValue("so")
    SO("so"),

    /**
     * Albanian
     * 
     */
    @XmlEnumValue("sq")
    SQ("sq"),

    /**
     * Serbian
     * 
     */
    @XmlEnumValue("sr")
    SR("sr"),

    /**
     * Siswati
     * 
     */
    @XmlEnumValue("ss")
    SS("ss"),

    /**
     * Sesotho
     * 
     */
    @XmlEnumValue("st")
    ST("st"),

    /**
     * Sundanese
     * 
     */
    @XmlEnumValue("su")
    SU("su"),

    /**
     * Swedish
     * 
     */
    @XmlEnumValue("sv")
    SV("sv"),

    /**
     * Swahili
     * 
     */
    @XmlEnumValue("sw")
    SW("sw"),

    /**
     * Tamil
     * 
     */
    @XmlEnumValue("ta")
    TA("ta"),

    /**
     * Telugu
     * 
     */
    @XmlEnumValue("te")
    TE("te"),

    /**
     * Tajik
     * 
     */
    @XmlEnumValue("tg")
    TG("tg"),

    /**
     * Thai
     * 
     */
    @XmlEnumValue("th")
    TH("th"),

    /**
     * Tigrinya
     * 
     */
    @XmlEnumValue("ti")
    TI("ti"),

    /**
     * Turkmen
     * 
     */
    @XmlEnumValue("tk")
    TK("tk"),

    /**
     * Tagalog
     * 
     */
    @XmlEnumValue("tl")
    TL("tl"),

    /**
     * Setswana
     * 
     */
    @XmlEnumValue("tn")
    TN("tn"),

    /**
     * Tonga
     * 
     */
    @XmlEnumValue("to")
    TO("to"),

    /**
     * Turkish
     * 
     */
    @XmlEnumValue("tr")
    TR("tr"),

    /**
     * Tsonga
     * 
     */
    @XmlEnumValue("ts")
    TS("ts"),

    /**
     * Tatar
     * 
     */
    @XmlEnumValue("tt")
    TT("tt"),

    /**
     * Twi
     * 
     */
    @XmlEnumValue("tw")
    TW("tw"),

    /**
     * Uigur
     * 
     */
    @XmlEnumValue("ug")
    UG("ug"),

    /**
     * Ukrainian
     * 
     */
    @XmlEnumValue("uk")
    UK("uk"),

    /**
     * Urdu
     * 
     */
    @XmlEnumValue("ur")
    UR("ur"),

    /**
     * Uzbek
     * 
     */
    @XmlEnumValue("uz")
    UZ("uz"),

    /**
     * Vietnamese
     * 
     */
    @XmlEnumValue("vi")
    VI("vi"),

    /**
     * Volapuk
     * 
     */
    @XmlEnumValue("vo")
    VO("vo"),

    /**
     * Wolof
     * 
     */
    @XmlEnumValue("wo")
    WO("wo"),

    /**
     * Xhosa
     * 
     */
    @XmlEnumValue("xh")
    XH("xh"),

    /**
     * Yiddish
     * 
     */
    @XmlEnumValue("yi")
    YI("yi"),

    /**
     * Yoruba
     * 
     */
    @XmlEnumValue("yo")
    YO("yo"),

    /**
     * Zhuang
     * 
     */
    @XmlEnumValue("za")
    ZA("za"),

    /**
     * Chinese
     * 
     */
    @XmlEnumValue("zh")
    ZH("zh"),

    /**
     * Zulu
     * 
     */
    @XmlEnumValue("zu")
    ZU("zu");
    private final String value;

    ISOLanguageCodeType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static ISOLanguageCodeType fromValue(String v) {
        for (ISOLanguageCodeType c: ISOLanguageCodeType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
