//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.03.11 at 12:27:12 AM CET 
//


package jxml;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for LegalEntityType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="LegalEntityType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}token">
 *     &lt;enumeration value="Physical person"/>
 *     &lt;enumeration value="Legal entity"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "LegalEntityType")
@XmlEnum
public enum LegalEntityType {

    @XmlEnumValue("Physical person")
    PHYSICAL_PERSON("Physical person"),
    @XmlEnumValue("Legal entity")
    LEGAL_ENTITY("Legal entity");
    private final String value;

    LegalEntityType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static LegalEntityType fromValue(String v) {
        for (LegalEntityType c: LegalEntityType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
