//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.03.11 at 12:27:12 AM CET 
//


package jxml;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for MarkEventType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="MarkEventType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="MarkEventDate" type="{http://www.w3.org/2001/XMLSchema}date"/>
 *         &lt;element name="MarkEventCode" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "MarkEventType", propOrder = {
    "markEventDate",
    "markEventCode"
})
public class MarkEventType {

    @XmlElement(name = "MarkEventDate", required = true)
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar markEventDate;
    @XmlElement(name = "MarkEventCode", required = true)
    protected String markEventCode;

    /**
     * Gets the value of the markEventDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getMarkEventDate() {
        return markEventDate;
    }

    /**
     * Sets the value of the markEventDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setMarkEventDate(XMLGregorianCalendar value) {
        this.markEventDate = value;
    }

    /**
     * Gets the value of the markEventCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMarkEventCode() {
        return markEventCode;
    }

    /**
     * Sets the value of the markEventCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMarkEventCode(String value) {
        this.markEventCode = value;
    }

}
