//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.03.11 at 12:27:12 AM CET 
//


package jxml;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for MarkCurrentStatusCodeType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="MarkCurrentStatusCodeType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}token">
 *     &lt;enumeration value="Application filed"/>
 *     &lt;enumeration value="Application published"/>
 *     &lt;enumeration value="Application opposed"/>
 *     &lt;enumeration value="Application refused"/>
 *     &lt;enumeration value="Application withdrawn"/>
 *     &lt;enumeration value="Appeal pending"/>
 *     &lt;enumeration value="Registered"/>
 *     &lt;enumeration value="Registration cancellation pending"/>
 *     &lt;enumeration value="Registration cancelled"/>
 *     &lt;enumeration value="Registration surrendered"/>
 *     &lt;enumeration value="Expired"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "MarkCurrentStatusCodeType")
@XmlEnum
public enum MarkCurrentStatusCodeType {

    @XmlEnumValue("Application filed")
    APPLICATION_FILED("Application filed"),
    @XmlEnumValue("Application published")
    APPLICATION_PUBLISHED("Application published"),
    @XmlEnumValue("Application opposed")
    APPLICATION_OPPOSED("Application opposed"),
    @XmlEnumValue("Application refused")
    APPLICATION_REFUSED("Application refused"),
    @XmlEnumValue("Application withdrawn")
    APPLICATION_WITHDRAWN("Application withdrawn"),
    @XmlEnumValue("Appeal pending")
    APPEAL_PENDING("Appeal pending"),
    @XmlEnumValue("Registered")
    REGISTERED("Registered"),
    @XmlEnumValue("Registration cancellation pending")
    REGISTRATION_CANCELLATION_PENDING("Registration cancellation pending"),
    @XmlEnumValue("Registration cancelled")
    REGISTRATION_CANCELLED("Registration cancelled"),
    @XmlEnumValue("Registration surrendered")
    REGISTRATION_SURRENDERED("Registration surrendered"),
    @XmlEnumValue("Ended")
    ENDED("Ended"),
    @XmlEnumValue("Expired")
    EXPIRED("Expired");
    private final String value;

    MarkCurrentStatusCodeType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static MarkCurrentStatusCodeType fromValue(String v) {
        for (MarkCurrentStatusCodeType c: MarkCurrentStatusCodeType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
