//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.03.11 at 12:27:12 AM CET 
//


package jxml;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the jxml package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Transaction_QNAME = new QName("http://www.oami.europa.eu/TM-Search", "Transaction");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: jxml
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link AddressType }
     * 
     */
    public AddressType createAddressType() {
        return new AddressType();
    }

    /**
     * Create an instance of {@link TradeMarkType }
     * 
     */
    public TradeMarkType createTradeMarkType() {
        return new TradeMarkType();
    }

    /**
     * Create an instance of {@link TransactionHeaderType }
     * 
     */
    public TransactionHeaderType createTransactionHeaderType() {
        return new TransactionHeaderType();
    }

    /**
     * Create an instance of {@link TransactionDataType }
     * 
     */
    public TransactionDataType createTransactionDataType() {
        return new TransactionDataType();
    }

    /**
     * Create an instance of {@link FreeFormatNameType }
     * 
     */
    public FreeFormatNameType createFreeFormatNameType() {
        return new FreeFormatNameType();
    }

    /**
     * Create an instance of {@link OppositionType }
     * 
     */
    public OppositionType createOppositionType() {
        return new OppositionType();
    }

    /**
     * Create an instance of {@link TransactionBodyType }
     * 
     */
    public TransactionBodyType createTransactionBodyType() {
        return new TransactionBodyType();
    }

    /**
     * Create an instance of {@link AddressBookType }
     * 
     */
    public AddressBookType createAddressBookType() {
        return new AddressBookType();
    }

    /**
     * Create an instance of {@link GoodsServicesType }
     * 
     */
    public GoodsServicesType createGoodsServicesType() {
        return new GoodsServicesType();
    }

    /**
     * Create an instance of {@link BasicRecordType }
     * 
     */
    public BasicRecordType createBasicRecordType() {
        return new BasicRecordType();
    }

    /**
     * Create an instance of {@link EarlierMarkType }
     * 
     */
    public EarlierMarkType createEarlierMarkType() {
        return new EarlierMarkType();
    }

    /**
     * Create an instance of {@link MarkImageCategoryType }
     * 
     */
    public MarkImageCategoryType createMarkImageCategoryType() {
        return new MarkImageCategoryType();
    }

    /**
     * Create an instance of {@link NameType }
     * 
     */
    public NameType createNameType() {
        return new NameType();
    }

    /**
     * Create an instance of {@link AppealType }
     * 
     */
    public AppealType createAppealType() {
        return new AppealType();
    }

    /**
     * Create an instance of {@link TransactionType }
     * 
     */
    public TransactionType createTransactionType() {
        return new TransactionType();
    }

    /**
     * Create an instance of {@link PriorityType }
     * 
     */
    public PriorityType createPriorityType() {
        return new PriorityType();
    }

    /**
     * Create an instance of {@link CorrespondenceAddressType }
     * 
     */
    public CorrespondenceAddressType createCorrespondenceAddressType() {
        return new CorrespondenceAddressType();
    }

    /**
     * Create an instance of {@link KeyType }
     * 
     */
    public KeyType createKeyType() {
        return new KeyType();
    }

    /**
     * Create an instance of {@link WordMarkSpecificationType }
     * 
     */
    public WordMarkSpecificationType createWordMarkSpecificationType() {
        return new WordMarkSpecificationType();
    }

    /**
     * Create an instance of {@link MarkEventType }
     * 
     */
    public MarkEventType createMarkEventType() {
        return new MarkEventType();
    }

    /**
     * Create an instance of {@link ApplicantType }
     * 
     */
    public ApplicantType createApplicantType() {
        return new ApplicantType();
    }

    /**
     * Create an instance of {@link MarkImageType }
     * 
     */
    public MarkImageType createMarkImageType() {
        return new MarkImageType();
    }

    /**
     * Create an instance of {@link AppealEventType }
     * 
     */
    public AppealEventType createAppealEventType() {
        return new AppealEventType();
    }

    /**
     * Create an instance of {@link ExhibitionPriorityType }
     * 
     */
    public ExhibitionPriorityType createExhibitionPriorityType() {
        return new ExhibitionPriorityType();
    }

    /**
     * Create an instance of {@link ClaimantType }
     * 
     */
    public ClaimantType createClaimantType() {
        return new ClaimantType();
    }

    /**
     * Create an instance of {@link PublicationType }
     * 
     */
    public PublicationType createPublicationType() {
        return new PublicationType();
    }

    /**
     * Create an instance of {@link RepresentativeType }
     * 
     */
    public RepresentativeType createRepresentativeType() {
        return new RepresentativeType();
    }

    /**
     * Create an instance of {@link URIType }
     * 
     */
    public URIType createURIType() {
        return new URIType();
    }

    /**
     * Create an instance of {@link TextType }
     * 
     */
    public TextType createTextType() {
        return new TextType();
    }

    /**
     * Create an instance of {@link OpponentType }
     * 
     */
    public OpponentType createOpponentType() {
        return new OpponentType();
    }

    /**
     * Create an instance of {@link FormattedNameAddressType }
     * 
     */
    public FormattedNameAddressType createFormattedNameAddressType() {
        return new FormattedNameAddressType();
    }

    /**
     * Create an instance of {@link MarkRecordType }
     * 
     */
    public MarkRecordType createMarkRecordType() {
        return new MarkRecordType();
    }

    /**
     * Create an instance of {@link DesignatedCountryType }
     * 
     */
    public DesignatedCountryType createDesignatedCountryType() {
        return new DesignatedCountryType();
    }

    /**
     * Create an instance of {@link CaseReferenceType }
     * 
     */
    public CaseReferenceType createCaseReferenceType() {
        return new CaseReferenceType();
    }

    /**
     * Create an instance of {@link AppellantType }
     * 
     */
    public AppellantType createAppellantType() {
        return new AppellantType();
    }

    /**
     * Create an instance of {@link ClassDescriptionType }
     * 
     */
    public ClassDescriptionType createClassDescriptionType() {
        return new ClassDescriptionType();
    }

    /**
     * Create an instance of {@link TransactionErrorType }
     * 
     */
    public TransactionErrorType createTransactionErrorType() {
        return new TransactionErrorType();
    }

    /**
     * Create an instance of {@link AddressType.FreeFormatAddress }
     * 
     */
    public AddressType.FreeFormatAddress createAddressTypeFreeFormatAddress() {
        return new AddressType.FreeFormatAddress();
    }

    /**
     * Create an instance of {@link AddressType.FormattedAddress }
     * 
     */
    public AddressType.FormattedAddress createAddressTypeFormattedAddress() {
        return new AddressType.FormattedAddress();
    }

    /**
     * Create an instance of {@link TradeMarkType.DesignatedCountryDetails }
     * 
     */
    public TradeMarkType.DesignatedCountryDetails createTradeMarkTypeDesignatedCountryDetails() {
        return new TradeMarkType.DesignatedCountryDetails();
    }

    /**
     * Create an instance of {@link TradeMarkType.MarkDescriptionDetails }
     * 
     */
    public TradeMarkType.MarkDescriptionDetails createTradeMarkTypeMarkDescriptionDetails() {
        return new TradeMarkType.MarkDescriptionDetails();
    }

    /**
     * Create an instance of {@link TradeMarkType.MarkDisclaimerDetails }
     * 
     */
    public TradeMarkType.MarkDisclaimerDetails createTradeMarkTypeMarkDisclaimerDetails() {
        return new TradeMarkType.MarkDisclaimerDetails();
    }

    /**
     * Create an instance of {@link TradeMarkType.MarkImageDetails }
     * 
     */
    public TradeMarkType.MarkImageDetails createTradeMarkTypeMarkImageDetails() {
        return new TradeMarkType.MarkImageDetails();
    }

    /**
     * Create an instance of {@link TradeMarkType.GoodsServicesDetails }
     * 
     */
    public TradeMarkType.GoodsServicesDetails createTradeMarkTypeGoodsServicesDetails() {
        return new TradeMarkType.GoodsServicesDetails();
    }

    /**
     * Create an instance of {@link TradeMarkType.PriorityDetails }
     * 
     */
    public TradeMarkType.PriorityDetails createTradeMarkTypePriorityDetails() {
        return new TradeMarkType.PriorityDetails();
    }

    /**
     * Create an instance of {@link TradeMarkType.ExhibitionPriorityDetails }
     * 
     */
    public TradeMarkType.ExhibitionPriorityDetails createTradeMarkTypeExhibitionPriorityDetails() {
        return new TradeMarkType.ExhibitionPriorityDetails();
    }

    /**
     * Create an instance of {@link TradeMarkType.PublicationDetails }
     * 
     */
    public TradeMarkType.PublicationDetails createTradeMarkTypePublicationDetails() {
        return new TradeMarkType.PublicationDetails();
    }

    /**
     * Create an instance of {@link TradeMarkType.ApplicantDetails }
     * 
     */
    public TradeMarkType.ApplicantDetails createTradeMarkTypeApplicantDetails() {
        return new TradeMarkType.ApplicantDetails();
    }

    /**
     * Create an instance of {@link TradeMarkType.RepresentativeDetails }
     * 
     */
    public TradeMarkType.RepresentativeDetails createTradeMarkTypeRepresentativeDetails() {
        return new TradeMarkType.RepresentativeDetails();
    }

    /**
     * Create an instance of {@link TradeMarkType.OppositionDetails }
     * 
     */
    public TradeMarkType.OppositionDetails createTradeMarkTypeOppositionDetails() {
        return new TradeMarkType.OppositionDetails();
    }

    /**
     * Create an instance of {@link TradeMarkType.MarkRecordDetails }
     * 
     */
    public TradeMarkType.MarkRecordDetails createTradeMarkTypeMarkRecordDetails() {
        return new TradeMarkType.MarkRecordDetails();
    }

    /**
     * Create an instance of {@link TradeMarkType.MarkEventDetails }
     * 
     */
    public TradeMarkType.MarkEventDetails createTradeMarkTypeMarkEventDetails() {
        return new TradeMarkType.MarkEventDetails();
    }

    /**
     * Create an instance of {@link TradeMarkType.AppealDetails }
     * 
     */
    public TradeMarkType.AppealDetails createTradeMarkTypeAppealDetails() {
        return new TradeMarkType.AppealDetails();
    }

    /**
     * Create an instance of {@link TransactionHeaderType.SenderDetails }
     * 
     */
    public TransactionHeaderType.SenderDetails createTransactionHeaderTypeSenderDetails() {
        return new TransactionHeaderType.SenderDetails();
    }

    /**
     * Create an instance of {@link TransactionDataType.TradeMarkDetails }
     * 
     */
    public TransactionDataType.TradeMarkDetails createTransactionDataTypeTradeMarkDetails() {
        return new TransactionDataType.TradeMarkDetails();
    }

    /**
     * Create an instance of {@link FreeFormatNameType.FreeFormatNameDetails }
     * 
     */
    public FreeFormatNameType.FreeFormatNameDetails createFreeFormatNameTypeFreeFormatNameDetails() {
        return new FreeFormatNameType.FreeFormatNameDetails();
    }

    /**
     * Create an instance of {@link OppositionType.EarlierMarkDetails }
     * 
     */
    public OppositionType.EarlierMarkDetails createOppositionTypeEarlierMarkDetails() {
        return new OppositionType.EarlierMarkDetails();
    }

    /**
     * Create an instance of {@link OppositionType.OpponentDetails }
     * 
     */
    public OppositionType.OpponentDetails createOppositionTypeOpponentDetails() {
        return new OppositionType.OpponentDetails();
    }

    /**
     * Create an instance of {@link OppositionType.RepresentativeDetails }
     * 
     */
    public OppositionType.RepresentativeDetails createOppositionTypeRepresentativeDetails() {
        return new OppositionType.RepresentativeDetails();
    }

    /**
     * Create an instance of {@link TransactionBodyType.TransactionErrorDetails }
     * 
     */
    public TransactionBodyType.TransactionErrorDetails createTransactionBodyTypeTransactionErrorDetails() {
        return new TransactionBodyType.TransactionErrorDetails();
    }

    /**
     * Create an instance of {@link TransactionBodyType.TransactionContentDetails }
     * 
     */
    public TransactionBodyType.TransactionContentDetails createTransactionBodyTypeTransactionContentDetails() {
        return new TransactionBodyType.TransactionContentDetails();
    }

    /**
     * Create an instance of {@link AddressBookType.ContactInformationDetails }
     * 
     */
    public AddressBookType.ContactInformationDetails createAddressBookTypeContactInformationDetails() {
        return new AddressBookType.ContactInformationDetails();
    }

    /**
     * Create an instance of {@link GoodsServicesType.ClassDescriptionDetails }
     * 
     */
    public GoodsServicesType.ClassDescriptionDetails createGoodsServicesTypeClassDescriptionDetails() {
        return new GoodsServicesType.ClassDescriptionDetails();
    }

    /**
     * Create an instance of {@link BasicRecordType.ClaimantDetails }
     * 
     */
    public BasicRecordType.ClaimantDetails createBasicRecordTypeClaimantDetails() {
        return new BasicRecordType.ClaimantDetails();
    }

    /**
     * Create an instance of {@link BasicRecordType.RepresentativeDetails }
     * 
     */
    public BasicRecordType.RepresentativeDetails createBasicRecordTypeRepresentativeDetails() {
        return new BasicRecordType.RepresentativeDetails();
    }

    /**
     * Create an instance of {@link EarlierMarkType.DesignatedCountryDetails }
     * 
     */
    public EarlierMarkType.DesignatedCountryDetails createEarlierMarkTypeDesignatedCountryDetails() {
        return new EarlierMarkType.DesignatedCountryDetails();
    }

    /**
     * Create an instance of {@link EarlierMarkType.OppositionGroundTextDetails }
     * 
     */
    public EarlierMarkType.OppositionGroundTextDetails createEarlierMarkTypeOppositionGroundTextDetails() {
        return new EarlierMarkType.OppositionGroundTextDetails();
    }

    /**
     * Create an instance of {@link MarkImageCategoryType.CategoryCodeDetails }
     * 
     */
    public MarkImageCategoryType.CategoryCodeDetails createMarkImageCategoryTypeCategoryCodeDetails() {
        return new MarkImageCategoryType.CategoryCodeDetails();
    }

    /**
     * Create an instance of {@link NameType.FormattedName }
     * 
     */
    public NameType.FormattedName createNameTypeFormattedName() {
        return new NameType.FormattedName();
    }

    /**
     * Create an instance of {@link AppealType.CaseReferenceDetails }
     * 
     */
    public AppealType.CaseReferenceDetails createAppealTypeCaseReferenceDetails() {
        return new AppealType.CaseReferenceDetails();
    }

    /**
     * Create an instance of {@link AppealType.AppellantDetails }
     * 
     */
    public AppealType.AppellantDetails createAppealTypeAppellantDetails() {
        return new AppealType.AppellantDetails();
    }

    /**
     * Create an instance of {@link AppealType.RepresentativeDetails }
     * 
     */
    public AppealType.RepresentativeDetails createAppealTypeRepresentativeDetails() {
        return new AppealType.RepresentativeDetails();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TransactionType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.oami.europa.eu/TM-Search", name = "Transaction")
    public JAXBElement<TransactionType> createTransaction(TransactionType value) {
        return new JAXBElement<TransactionType>(_Transaction_QNAME, TransactionType.class, null, value);
    }

}
