//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.03.11 at 12:27:12 AM CET 
//


package jxml;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for OppositionType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="OppositionType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="OppositionIdentifier" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="OppositionDate" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/>
 *         &lt;element name="OppositionReference" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="ProceedingLanguageCode" type="{http://www.oami.europa.eu/TM-Search}ISOLanguageCodeType" minOccurs="0"/>
 *         &lt;element name="OppositionBasisCode" type="{http://www.oami.europa.eu/TM-Search}OppositionBasisCodeType" minOccurs="0"/>
 *         &lt;element name="OppositionGroundText" type="{http://www.oami.europa.eu/TM-Search}TextType" minOccurs="0"/>
 *         &lt;element name="OppositionCurrentStatusCode" type="{http://www.oami.europa.eu/TM-Search}OppositionCurrentStatusCodeType" minOccurs="0"/>
 *         &lt;element name="OppositionCurrentStatusDate" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/>
 *         &lt;element name="OppositionDecisionStatusCode" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="EarlierMarkDetails" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="EarlierMark" type="{http://www.oami.europa.eu/TM-Search}EarlierMarkType" maxOccurs="unbounded"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="OpponentDetails" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="Opponent" type="{http://www.oami.europa.eu/TM-Search}OpponentType" maxOccurs="unbounded"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="RepresentativeDetails" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="Representative" type="{http://www.oami.europa.eu/TM-Search}RepresentativeType" maxOccurs="unbounded"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "OppositionType", propOrder = {
    "oppositionIdentifier",
    "oppositionDate",
    "oppositionReference",
    "proceedingLanguageCode",
    "oppositionBasisCode",
    "oppositionGroundText",
    "oppositionCurrentStatusCode",
    "oppositionCurrentStatusDate",
    "oppositionDecisionStatusCode",
    "earlierMarkDetails",
    "opponentDetails",
    "representativeDetails"
})
public class OppositionType {

    @XmlElement(name = "OppositionIdentifier")
    protected String oppositionIdentifier;
    @XmlElement(name = "OppositionDate")
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar oppositionDate;
    @XmlElement(name = "OppositionReference")
    protected String oppositionReference;
    @XmlElement(name = "ProceedingLanguageCode")
    @XmlSchemaType(name = "NMTOKEN")
    protected ISOLanguageCodeType proceedingLanguageCode;
    @XmlElement(name = "OppositionBasisCode")
    @XmlSchemaType(name = "token")
    protected OppositionBasisCodeType oppositionBasisCode;
    @XmlElement(name = "OppositionGroundText")
    protected TextType oppositionGroundText;
    @XmlElement(name = "OppositionCurrentStatusCode")
    @XmlSchemaType(name = "token")
    protected OppositionCurrentStatusCodeType oppositionCurrentStatusCode;
    @XmlElement(name = "OppositionCurrentStatusDate")
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar oppositionCurrentStatusDate;
    @XmlElement(name = "OppositionDecisionStatusCode")
    protected String oppositionDecisionStatusCode;
    @XmlElement(name = "EarlierMarkDetails")
    protected OppositionType.EarlierMarkDetails earlierMarkDetails;
    @XmlElement(name = "OpponentDetails")
    protected OppositionType.OpponentDetails opponentDetails;
    @XmlElement(name = "RepresentativeDetails")
    protected OppositionType.RepresentativeDetails representativeDetails;

    /**
     * Gets the value of the oppositionIdentifier property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOppositionIdentifier() {
        return oppositionIdentifier;
    }

    /**
     * Sets the value of the oppositionIdentifier property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOppositionIdentifier(String value) {
        this.oppositionIdentifier = value;
    }

    /**
     * Gets the value of the oppositionDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getOppositionDate() {
        return oppositionDate;
    }

    /**
     * Sets the value of the oppositionDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setOppositionDate(XMLGregorianCalendar value) {
        this.oppositionDate = value;
    }

    /**
     * Gets the value of the oppositionReference property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOppositionReference() {
        return oppositionReference;
    }

    /**
     * Sets the value of the oppositionReference property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOppositionReference(String value) {
        this.oppositionReference = value;
    }

    /**
     * Gets the value of the proceedingLanguageCode property.
     * 
     * @return
     *     possible object is
     *     {@link ISOLanguageCodeType }
     *     
     */
    public ISOLanguageCodeType getProceedingLanguageCode() {
        return proceedingLanguageCode;
    }

    /**
     * Sets the value of the proceedingLanguageCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link ISOLanguageCodeType }
     *     
     */
    public void setProceedingLanguageCode(ISOLanguageCodeType value) {
        this.proceedingLanguageCode = value;
    }

    /**
     * Gets the value of the oppositionBasisCode property.
     * 
     * @return
     *     possible object is
     *     {@link OppositionBasisCodeType }
     *     
     */
    public OppositionBasisCodeType getOppositionBasisCode() {
        return oppositionBasisCode;
    }

    /**
     * Sets the value of the oppositionBasisCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link OppositionBasisCodeType }
     *     
     */
    public void setOppositionBasisCode(OppositionBasisCodeType value) {
        this.oppositionBasisCode = value;
    }

    /**
     * Gets the value of the oppositionGroundText property.
     * 
     * @return
     *     possible object is
     *     {@link TextType }
     *     
     */
    public TextType getOppositionGroundText() {
        return oppositionGroundText;
    }

    /**
     * Sets the value of the oppositionGroundText property.
     * 
     * @param value
     *     allowed object is
     *     {@link TextType }
     *     
     */
    public void setOppositionGroundText(TextType value) {
        this.oppositionGroundText = value;
    }

    /**
     * Gets the value of the oppositionCurrentStatusCode property.
     * 
     * @return
     *     possible object is
     *     {@link OppositionCurrentStatusCodeType }
     *     
     */
    public OppositionCurrentStatusCodeType getOppositionCurrentStatusCode() {
        return oppositionCurrentStatusCode;
    }

    /**
     * Sets the value of the oppositionCurrentStatusCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link OppositionCurrentStatusCodeType }
     *     
     */
    public void setOppositionCurrentStatusCode(OppositionCurrentStatusCodeType value) {
        this.oppositionCurrentStatusCode = value;
    }

    /**
     * Gets the value of the oppositionCurrentStatusDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getOppositionCurrentStatusDate() {
        return oppositionCurrentStatusDate;
    }

    /**
     * Sets the value of the oppositionCurrentStatusDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setOppositionCurrentStatusDate(XMLGregorianCalendar value) {
        this.oppositionCurrentStatusDate = value;
    }

    /**
     * Gets the value of the oppositionDecisionStatusCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOppositionDecisionStatusCode() {
        return oppositionDecisionStatusCode;
    }

    /**
     * Sets the value of the oppositionDecisionStatusCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOppositionDecisionStatusCode(String value) {
        this.oppositionDecisionStatusCode = value;
    }

    /**
     * Gets the value of the earlierMarkDetails property.
     * 
     * @return
     *     possible object is
     *     {@link OppositionType.EarlierMarkDetails }
     *     
     */
    public OppositionType.EarlierMarkDetails getEarlierMarkDetails() {
        return earlierMarkDetails;
    }

    /**
     * Sets the value of the earlierMarkDetails property.
     * 
     * @param value
     *     allowed object is
     *     {@link OppositionType.EarlierMarkDetails }
     *     
     */
    public void setEarlierMarkDetails(OppositionType.EarlierMarkDetails value) {
        this.earlierMarkDetails = value;
    }

    /**
     * Gets the value of the opponentDetails property.
     * 
     * @return
     *     possible object is
     *     {@link OppositionType.OpponentDetails }
     *     
     */
    public OppositionType.OpponentDetails getOpponentDetails() {
        return opponentDetails;
    }

    /**
     * Sets the value of the opponentDetails property.
     * 
     * @param value
     *     allowed object is
     *     {@link OppositionType.OpponentDetails }
     *     
     */
    public void setOpponentDetails(OppositionType.OpponentDetails value) {
        this.opponentDetails = value;
    }

    /**
     * Gets the value of the representativeDetails property.
     * 
     * @return
     *     possible object is
     *     {@link OppositionType.RepresentativeDetails }
     *     
     */
    public OppositionType.RepresentativeDetails getRepresentativeDetails() {
        return representativeDetails;
    }

    /**
     * Sets the value of the representativeDetails property.
     * 
     * @param value
     *     allowed object is
     *     {@link OppositionType.RepresentativeDetails }
     *     
     */
    public void setRepresentativeDetails(OppositionType.RepresentativeDetails value) {
        this.representativeDetails = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="EarlierMark" type="{http://www.oami.europa.eu/TM-Search}EarlierMarkType" maxOccurs="unbounded"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "earlierMark"
    })
    public static class EarlierMarkDetails {

        @XmlElement(name = "EarlierMark", required = true)
        protected List<EarlierMarkType> earlierMark;

        /**
         * Gets the value of the earlierMark property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the earlierMark property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getEarlierMark().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link EarlierMarkType }
         * 
         * 
         */
        public List<EarlierMarkType> getEarlierMark() {
            if (earlierMark == null) {
                earlierMark = new ArrayList<EarlierMarkType>();
            }
            return this.earlierMark;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="Opponent" type="{http://www.oami.europa.eu/TM-Search}OpponentType" maxOccurs="unbounded"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "opponent"
    })
    public static class OpponentDetails {

        @XmlElement(name = "Opponent", required = true)
        protected List<OpponentType> opponent;

        /**
         * Gets the value of the opponent property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the opponent property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getOpponent().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link OpponentType }
         * 
         * 
         */
        public List<OpponentType> getOpponent() {
            if (opponent == null) {
                opponent = new ArrayList<OpponentType>();
            }
            return this.opponent;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="Representative" type="{http://www.oami.europa.eu/TM-Search}RepresentativeType" maxOccurs="unbounded"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "representative"
    })
    public static class RepresentativeDetails {

        @XmlElement(name = "Representative", required = true)
        protected List<RepresentativeType> representative;

        /**
         * Gets the value of the representative property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the representative property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getRepresentative().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link RepresentativeType }
         * 
         * 
         */
        public List<RepresentativeType> getRepresentative() {
            if (representative == null) {
                representative = new ArrayList<RepresentativeType>();
            }
            return this.representative;
        }

    }

}
