//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.03.11 at 12:27:12 AM CET 
//


package jxml;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for PriorityType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="PriorityType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="PriorityCountryCode">
 *           &lt;simpleType>
 *             &lt;union memberTypes=" {http://www.oami.europa.eu/TM-Search}WIPOST3CodeType {http://www.oami.europa.eu/TM-Search}WIPOFormerST3CodeType">
 *             &lt;/union>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="PriorityNumber" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="PriorityDate" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/>
 *         &lt;element name="PriorityPartialIndicator" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="PriorityPartialGoodsServices" type="{http://www.oami.europa.eu/TM-Search}GoodsServicesType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PriorityType", propOrder = {
    "priorityCountryCode",
    "priorityNumber",
    "priorityDate",
    "priorityPartialIndicator",
    "priorityPartialGoodsServices"
})
public class PriorityType {

    @XmlElement(name = "PriorityCountryCode", required = true)
    protected String priorityCountryCode;
    @XmlElement(name = "PriorityNumber")
    protected String priorityNumber;
    @XmlElement(name = "PriorityDate")
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar priorityDate;
    @XmlElement(name = "PriorityPartialIndicator")
    protected Boolean priorityPartialIndicator;
    @XmlElement(name = "PriorityPartialGoodsServices")
    protected GoodsServicesType priorityPartialGoodsServices;

    /**
     * Gets the value of the priorityCountryCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPriorityCountryCode() {
        return priorityCountryCode;
    }

    /**
     * Sets the value of the priorityCountryCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPriorityCountryCode(String value) {
        this.priorityCountryCode = value;
    }

    /**
     * Gets the value of the priorityNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPriorityNumber() {
        return priorityNumber;
    }

    /**
     * Sets the value of the priorityNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPriorityNumber(String value) {
        this.priorityNumber = value;
    }

    /**
     * Gets the value of the priorityDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getPriorityDate() {
        return priorityDate;
    }

    /**
     * Sets the value of the priorityDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setPriorityDate(XMLGregorianCalendar value) {
        this.priorityDate = value;
    }

    /**
     * Gets the value of the priorityPartialIndicator property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isPriorityPartialIndicator() {
        return priorityPartialIndicator;
    }

    /**
     * Sets the value of the priorityPartialIndicator property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setPriorityPartialIndicator(Boolean value) {
        this.priorityPartialIndicator = value;
    }

    /**
     * Gets the value of the priorityPartialGoodsServices property.
     * 
     * @return
     *     possible object is
     *     {@link GoodsServicesType }
     *     
     */
    public GoodsServicesType getPriorityPartialGoodsServices() {
        return priorityPartialGoodsServices;
    }

    /**
     * Sets the value of the priorityPartialGoodsServices property.
     * 
     * @param value
     *     allowed object is
     *     {@link GoodsServicesType }
     *     
     */
    public void setPriorityPartialGoodsServices(GoodsServicesType value) {
        this.priorityPartialGoodsServices = value;
    }

}
