//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.03.11 at 12:27:12 AM CET 
//


package jxml;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for PriorityStatusCodeType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="PriorityStatusCodeType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}token">
 *     &lt;enumeration value="Claimed"/>
 *     &lt;enumeration value="Abandoned"/>
 *     &lt;enumeration value="Accepted"/>
 *     &lt;enumeration value="Partially Refused"/>
 *     &lt;enumeration value="Refused"/>
 *     &lt;enumeration value="Undefined"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "PriorityStatusCodeType")
@XmlEnum
public enum PriorityStatusCodeType {

    @XmlEnumValue("Claimed")
    CLAIMED("Claimed"),
    @XmlEnumValue("Abandoned")
    ABANDONED("Abandoned"),
    @XmlEnumValue("Accepted")
    ACCEPTED("Accepted"),
    @XmlEnumValue("Partially Refused")
    PARTIALLY_REFUSED("Partially Refused"),
    @XmlEnumValue("Refused")
    REFUSED("Refused"),
    @XmlEnumValue("Undefined")
    UNDEFINED("Undefined");
    private final String value;

    PriorityStatusCodeType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static PriorityStatusCodeType fromValue(String v) {
        for (PriorityStatusCodeType c: PriorityStatusCodeType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
