//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.03.11 at 12:27:12 AM CET 
//


package jxml;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlList;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for RepresentativeType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="RepresentativeType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="RepresentativeIdentifier" type="{http://www.w3.org/2001/XMLSchema}token" minOccurs="0"/>
 *         &lt;element name="RepresentativeKindCode" type="{http://www.oami.europa.eu/TM-Search}RepresentativeKindCodeType" minOccurs="0"/>
 *         &lt;element name="RepresentativeNationalityCode" type="{http://www.oami.europa.eu/TM-Search}NationalityCodeType" minOccurs="0"/>
 *         &lt;element name="RepresentativeLegalEntity" type="{http://www.oami.europa.eu/TM-Search}LegalEntityType" minOccurs="0"/>
 *         &lt;element name="RepresentativeIncorporationCountryCode" type="{http://www.oami.europa.eu/TM-Search}ExtendedISOCountryCodeType" minOccurs="0"/>
 *         &lt;element name="RepresentativeIncorporationState" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="RepresentativeAddressBook" type="{http://www.oami.europa.eu/TM-Search}AddressBookType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "RepresentativeType", propOrder = {
    "representativeIdentifier",
    "representativeKindCode",
    "representativeNationalityCode",
    "representativeLegalEntity",
    "representativeIncorporationCountryCode",
    "representativeIncorporationState",
    "representativeAddressBook"
})
public class RepresentativeType {

    @XmlElement(name = "RepresentativeIdentifier")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "token")
    protected String representativeIdentifier;
    @XmlElement(name = "RepresentativeKindCode")
    @XmlSchemaType(name = "token")
    protected RepresentativeKindCodeType representativeKindCode;
    @XmlList
    @XmlElement(name = "RepresentativeNationalityCode")
    @XmlSchemaType(name = "anySimpleType")
    protected List<String> representativeNationalityCode;
    @XmlElement(name = "RepresentativeLegalEntity")
    @XmlSchemaType(name = "token")
    protected LegalEntityType representativeLegalEntity;
    @XmlElement(name = "RepresentativeIncorporationCountryCode")
    @XmlSchemaType(name = "anySimpleType")
    protected String representativeIncorporationCountryCode;
    @XmlElement(name = "RepresentativeIncorporationState")
    protected String representativeIncorporationState;
    @XmlElement(name = "RepresentativeAddressBook")
    protected AddressBookType representativeAddressBook;

    /**
     * Gets the value of the representativeIdentifier property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRepresentativeIdentifier() {
        return representativeIdentifier;
    }

    /**
     * Sets the value of the representativeIdentifier property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRepresentativeIdentifier(String value) {
        this.representativeIdentifier = value;
    }

    /**
     * Gets the value of the representativeKindCode property.
     * 
     * @return
     *     possible object is
     *     {@link RepresentativeKindCodeType }
     *     
     */
    public RepresentativeKindCodeType getRepresentativeKindCode() {
        return representativeKindCode;
    }

    /**
     * Sets the value of the representativeKindCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link RepresentativeKindCodeType }
     *     
     */
    public void setRepresentativeKindCode(RepresentativeKindCodeType value) {
        this.representativeKindCode = value;
    }

    /**
     * Gets the value of the representativeNationalityCode property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the representativeNationalityCode property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getRepresentativeNationalityCode().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getRepresentativeNationalityCode() {
        if (representativeNationalityCode == null) {
            representativeNationalityCode = new ArrayList<String>();
        }
        return this.representativeNationalityCode;
    }

    /**
     * Gets the value of the representativeLegalEntity property.
     * 
     * @return
     *     possible object is
     *     {@link LegalEntityType }
     *     
     */
    public LegalEntityType getRepresentativeLegalEntity() {
        return representativeLegalEntity;
    }

    /**
     * Sets the value of the representativeLegalEntity property.
     * 
     * @param value
     *     allowed object is
     *     {@link LegalEntityType }
     *     
     */
    public void setRepresentativeLegalEntity(LegalEntityType value) {
        this.representativeLegalEntity = value;
    }

    /**
     * Gets the value of the representativeIncorporationCountryCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRepresentativeIncorporationCountryCode() {
        return representativeIncorporationCountryCode;
    }

    /**
     * Sets the value of the representativeIncorporationCountryCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRepresentativeIncorporationCountryCode(String value) {
        this.representativeIncorporationCountryCode = value;
    }

    /**
     * Gets the value of the representativeIncorporationState property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRepresentativeIncorporationState() {
        return representativeIncorporationState;
    }

    /**
     * Sets the value of the representativeIncorporationState property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRepresentativeIncorporationState(String value) {
        this.representativeIncorporationState = value;
    }

    /**
     * Gets the value of the representativeAddressBook property.
     * 
     * @return
     *     possible object is
     *     {@link AddressBookType }
     *     
     */
    public AddressBookType getRepresentativeAddressBook() {
        return representativeAddressBook;
    }

    /**
     * Sets the value of the representativeAddressBook property.
     * 
     * @param value
     *     allowed object is
     *     {@link AddressBookType }
     *     
     */
    public void setRepresentativeAddressBook(AddressBookType value) {
        this.representativeAddressBook = value;
    }

}
