//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.03.11 at 12:27:12 AM CET 
//


package jxml;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for TradeMarkType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="TradeMarkType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="RegistrationOfficeCode" type="{http://www.oami.europa.eu/TM-Search}WIPOST3CodeType" minOccurs="0"/>
 *         &lt;element name="InternationalMarkIndicator" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="ReceivingOfficeCode" type="{http://www.oami.europa.eu/TM-Search}WIPOST3CodeType" minOccurs="0"/>
 *         &lt;element name="ReceivingOfficeDate" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/>
 *         &lt;element name="ApplicationNumber" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="ApplicationDate" type="{http://www.w3.org/2001/XMLSchema}date"/>
 *         &lt;element name="RegistrationNumber" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="RegistrationDate" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/>
 *         &lt;element name="IPRKind" type="{http://www.oami.europa.eu/TM-Search}IPRKindType" minOccurs="0"/>
 *         &lt;element name="FilingPlace" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="ApplicationReference" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="ApplicationLanguageCode" type="{http://www.oami.europa.eu/TM-Search}ExtendedISOLanguageCodeType" minOccurs="0"/>
 *         &lt;element name="ExpiryDate" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/>
 *         &lt;element name="TerminationDate" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/>
 *         &lt;element name="MarkCurrentStatusCode" type="{http://www.oami.europa.eu/TM-Search}MarkCurrentStatusCodeType"/>
 *         &lt;element name="MarkCurrentStatusDate" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/>
 *         &lt;element name="DesignatedCountryDetails" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="DesignatedCountry" type="{http://www.oami.europa.eu/TM-Search}DesignatedCountryType" maxOccurs="unbounded"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="KindMark" type="{http://www.oami.europa.eu/TM-Search}KindMarkType" minOccurs="0"/>
 *         &lt;element name="MarkFeature" type="{http://www.oami.europa.eu/TM-Search}MarkFeatureType" minOccurs="0"/>
 *         &lt;element name="MarkDescriptionDetails" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="MarkDescription" type="{http://www.oami.europa.eu/TM-Search}TextType" maxOccurs="unbounded"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="MarkDisclaimerDetails" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="MarkDisclaimer" type="{http://www.oami.europa.eu/TM-Search}TextType" maxOccurs="unbounded"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="SpecialCircumstanceText" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="TotalMarkSeries" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/>
 *         &lt;element name="TradeDistinctivenessIndicator" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="TradeDistinctivenessText" type="{http://www.oami.europa.eu/TM-Search}TextType" minOccurs="0"/>
 *         &lt;element name="Comment" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="OppositionPeriodStartDate" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/>
 *         &lt;element name="OppositionPeriodEndDate" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/>
 *         &lt;element name="WordMarkSpecification" type="{http://www.oami.europa.eu/TM-Search}WordMarkSpecificationType" minOccurs="0"/>
 *         &lt;element name="MarkImageDetails" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="MarkImage" type="{http://www.oami.europa.eu/TM-Search}MarkImageType" maxOccurs="unbounded"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="GoodsServicesDetails" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="GoodsServices" type="{http://www.oami.europa.eu/TM-Search}GoodsServicesType"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="PriorityDetails" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="Priority" type="{http://www.oami.europa.eu/TM-Search}PriorityType" maxOccurs="unbounded"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="ExhibitionPriorityDetails" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="ExhibitionPriority" type="{http://www.oami.europa.eu/TM-Search}ExhibitionPriorityType" maxOccurs="unbounded"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="PublicationDetails" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="Publication" type="{http://www.oami.europa.eu/TM-Search}PublicationType" maxOccurs="unbounded"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="ApplicantDetails" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="Applicant" type="{http://www.oami.europa.eu/TM-Search}ApplicantType" maxOccurs="unbounded"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="RepresentativeDetails" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="Representative" type="{http://www.oami.europa.eu/TM-Search}RepresentativeType" maxOccurs="unbounded"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="CorrespondenceAddress" type="{http://www.oami.europa.eu/TM-Search}CorrespondenceAddressType"/>
 *         &lt;element name="OppositionDetails" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="Opposition" type="{http://www.oami.europa.eu/TM-Search}OppositionType" maxOccurs="unbounded"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="MarkRecordDetails" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="MarkRecord" type="{http://www.oami.europa.eu/TM-Search}MarkRecordType" maxOccurs="unbounded"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="MarkEventDetails" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="MarkEvent" type="{http://www.oami.europa.eu/TM-Search}MarkEventType" maxOccurs="unbounded"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="AppealDetails" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="Appeal" type="{http://www.oami.europa.eu/TM-Search}AppealType" maxOccurs="unbounded"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *       &lt;attribute name="operationCode" type="{http://www.oami.europa.eu/TM-Search}OperationCodeType" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TradeMarkType", propOrder = {
    "registrationOfficeCode",
    "internationalMarkIndicator",
    "receivingOfficeCode",
    "receivingOfficeDate",
    "applicationNumber",
    "applicationDate",
    "registrationNumber",
    "registrationDate",
    "iprKind",
    "filingPlace",
    "applicationReference",
    "applicationLanguageCode",
    "expiryDate",
    "terminationDate",
    "markCurrentStatusCode",
    "markCurrentStatusDate",
    "designatedCountryDetails",
    "kindMark",
    "markFeature",
    "markDescriptionDetails",
    "markDisclaimerDetails",
    "specialCircumstanceText",
    "totalMarkSeries",
    "tradeDistinctivenessIndicator",
    "tradeDistinctivenessText",
    "comment",
    "oppositionPeriodStartDate",
    "oppositionPeriodEndDate",
    "wordMarkSpecification",
    "markImageDetails",
    "goodsServicesDetails",
    "priorityDetails",
    "exhibitionPriorityDetails",
    "publicationDetails",
    "applicantDetails",
    "representativeDetails",
    "correspondenceAddress",
    "oppositionDetails",
    "markRecordDetails",
    "markEventDetails",
    "appealDetails"
})
public class TradeMarkType {

    @XmlElement(name = "RegistrationOfficeCode")
    @XmlSchemaType(name = "NMTOKEN")
    protected WIPOST3CodeType registrationOfficeCode;
    @XmlElement(name = "InternationalMarkIndicator")
    protected Boolean internationalMarkIndicator;
    @XmlElement(name = "ReceivingOfficeCode")
    @XmlSchemaType(name = "NMTOKEN")
    protected WIPOST3CodeType receivingOfficeCode;
    @XmlElement(name = "ReceivingOfficeDate")
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar receivingOfficeDate;
    @XmlElement(name = "ApplicationNumber")
    protected String applicationNumber;
    @XmlElement(name = "ApplicationDate", required = true)
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar applicationDate;
    @XmlElement(name = "RegistrationNumber")
    protected String registrationNumber;
    @XmlElement(name = "RegistrationDate")
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar registrationDate;
    @XmlElement(name = "IPRKind", defaultValue = "Trade mark")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "token")
    protected String iprKind;
    @XmlElement(name = "FilingPlace")
    protected String filingPlace;
    @XmlElement(name = "ApplicationReference")
    protected String applicationReference;
    @XmlElement(name = "ApplicationLanguageCode")
    @XmlSchemaType(name = "anySimpleType")
    protected String applicationLanguageCode;
    @XmlElement(name = "ExpiryDate")
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar expiryDate;
    @XmlElement(name = "TerminationDate")
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar terminationDate;
    @XmlElement(name = "MarkCurrentStatusCode", required = true)
    @XmlSchemaType(name = "token")
    protected MarkCurrentStatusCodeType markCurrentStatusCode;
    @XmlElement(name = "MarkCurrentStatusDate")
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar markCurrentStatusDate;
    @XmlElement(name = "DesignatedCountryDetails")
    protected TradeMarkType.DesignatedCountryDetails designatedCountryDetails;
    @XmlElement(name = "KindMark")
    @XmlSchemaType(name = "token")
    protected KindMarkType kindMark;
    @XmlElement(name = "MarkFeature")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "token")
    protected String markFeature;
    @XmlElement(name = "MarkDescriptionDetails")
    protected TradeMarkType.MarkDescriptionDetails markDescriptionDetails;
    @XmlElement(name = "MarkDisclaimerDetails")
    protected TradeMarkType.MarkDisclaimerDetails markDisclaimerDetails;
    @XmlElement(name = "SpecialCircumstanceText")
    protected String specialCircumstanceText;
    @XmlElement(name = "TotalMarkSeries")
    protected BigInteger totalMarkSeries;
    @XmlElement(name = "TradeDistinctivenessIndicator")
    protected Boolean tradeDistinctivenessIndicator;
    @XmlElement(name = "TradeDistinctivenessText")
    protected TextType tradeDistinctivenessText;
    @XmlElement(name = "Comment")
    protected String comment;
    @XmlElement(name = "OppositionPeriodStartDate")
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar oppositionPeriodStartDate;
    @XmlElement(name = "OppositionPeriodEndDate")
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar oppositionPeriodEndDate;
    @XmlElement(name = "WordMarkSpecification")
    protected WordMarkSpecificationType wordMarkSpecification;
    @XmlElement(name = "MarkImageDetails")
    protected TradeMarkType.MarkImageDetails markImageDetails;
    @XmlElement(name = "GoodsServicesDetails")
    protected TradeMarkType.GoodsServicesDetails goodsServicesDetails;
    @XmlElement(name = "PriorityDetails")
    protected TradeMarkType.PriorityDetails priorityDetails;
    @XmlElement(name = "ExhibitionPriorityDetails")
    protected TradeMarkType.ExhibitionPriorityDetails exhibitionPriorityDetails;
    @XmlElement(name = "PublicationDetails")
    protected TradeMarkType.PublicationDetails publicationDetails;
    @XmlElement(name = "ApplicantDetails")
    protected TradeMarkType.ApplicantDetails applicantDetails;
    @XmlElement(name = "RepresentativeDetails")
    protected TradeMarkType.RepresentativeDetails representativeDetails;
    @XmlElement(name = "CorrespondenceAddress", required = true)
    protected CorrespondenceAddressType correspondenceAddress;
    @XmlElement(name = "OppositionDetails")
    protected TradeMarkType.OppositionDetails oppositionDetails;
    @XmlElement(name = "MarkRecordDetails")
    protected TradeMarkType.MarkRecordDetails markRecordDetails;
    @XmlElement(name = "MarkEventDetails")
    protected TradeMarkType.MarkEventDetails markEventDetails;
    @XmlElement(name = "AppealDetails")
    protected TradeMarkType.AppealDetails appealDetails;
    @XmlAttribute(name = "operationCode")
    protected OperationCodeType operationCode;

    /**
     * Gets the value of the registrationOfficeCode property.
     * 
     * @return
     *     possible object is
     *     {@link WIPOST3CodeType }
     *     
     */
    public WIPOST3CodeType getRegistrationOfficeCode() {
        return registrationOfficeCode;
    }

    /**
     * Sets the value of the registrationOfficeCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link WIPOST3CodeType }
     *     
     */
    public void setRegistrationOfficeCode(WIPOST3CodeType value) {
        this.registrationOfficeCode = value;
    }

    /**
     * Gets the value of the internationalMarkIndicator property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isInternationalMarkIndicator() {
        return internationalMarkIndicator;
    }

    /**
     * Sets the value of the internationalMarkIndicator property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setInternationalMarkIndicator(Boolean value) {
        this.internationalMarkIndicator = value;
    }

    /**
     * Gets the value of the receivingOfficeCode property.
     * 
     * @return
     *     possible object is
     *     {@link WIPOST3CodeType }
     *     
     */
    public WIPOST3CodeType getReceivingOfficeCode() {
        return receivingOfficeCode;
    }

    /**
     * Sets the value of the receivingOfficeCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link WIPOST3CodeType }
     *     
     */
    public void setReceivingOfficeCode(WIPOST3CodeType value) {
        this.receivingOfficeCode = value;
    }

    /**
     * Gets the value of the receivingOfficeDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getReceivingOfficeDate() {
        return receivingOfficeDate;
    }

    /**
     * Sets the value of the receivingOfficeDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setReceivingOfficeDate(XMLGregorianCalendar value) {
        this.receivingOfficeDate = value;
    }

    /**
     * Gets the value of the applicationNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getApplicationNumber() {
        return applicationNumber;
    }

    /**
     * Sets the value of the applicationNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setApplicationNumber(String value) {
        this.applicationNumber = value;
    }

    /**
     * Gets the value of the applicationDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getApplicationDate() {
        return applicationDate;
    }

    /**
     * Sets the value of the applicationDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setApplicationDate(XMLGregorianCalendar value) {
        this.applicationDate = value;
    }

    /**
     * Gets the value of the registrationNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRegistrationNumber() {
        return registrationNumber;
    }

    /**
     * Sets the value of the registrationNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRegistrationNumber(String value) {
        this.registrationNumber = value;
    }

    /**
     * Gets the value of the registrationDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getRegistrationDate() {
        return registrationDate;
    }

    /**
     * Sets the value of the registrationDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setRegistrationDate(XMLGregorianCalendar value) {
        this.registrationDate = value;
    }

    /**
     * Gets the value of the iprKind property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIPRKind() {
        return iprKind;
    }

    /**
     * Sets the value of the iprKind property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIPRKind(String value) {
        this.iprKind = value;
    }

    /**
     * Gets the value of the filingPlace property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFilingPlace() {
        return filingPlace;
    }

    /**
     * Sets the value of the filingPlace property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFilingPlace(String value) {
        this.filingPlace = value;
    }

    /**
     * Gets the value of the applicationReference property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getApplicationReference() {
        return applicationReference;
    }

    /**
     * Sets the value of the applicationReference property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setApplicationReference(String value) {
        this.applicationReference = value;
    }

    /**
     * Gets the value of the applicationLanguageCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getApplicationLanguageCode() {
        return applicationLanguageCode;
    }

    /**
     * Sets the value of the applicationLanguageCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setApplicationLanguageCode(String value) {
        this.applicationLanguageCode = value;
    }

    /**
     * Gets the value of the expiryDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getExpiryDate() {
        return expiryDate;
    }

    /**
     * Sets the value of the expiryDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setExpiryDate(XMLGregorianCalendar value) {
        this.expiryDate = value;
    }

    /**
     * Gets the value of the terminationDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getTerminationDate() {
        return terminationDate;
    }

    /**
     * Sets the value of the terminationDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setTerminationDate(XMLGregorianCalendar value) {
        this.terminationDate = value;
    }

    /**
     * Gets the value of the markCurrentStatusCode property.
     * 
     * @return
     *     possible object is
     *     {@link MarkCurrentStatusCodeType }
     *     
     */
    public MarkCurrentStatusCodeType getMarkCurrentStatusCode() {
        return markCurrentStatusCode;
    }

    /**
     * Sets the value of the markCurrentStatusCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link MarkCurrentStatusCodeType }
     *     
     */
    public void setMarkCurrentStatusCode(MarkCurrentStatusCodeType value) {
        this.markCurrentStatusCode = value;
    }

    /**
     * Gets the value of the markCurrentStatusDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getMarkCurrentStatusDate() {
        return markCurrentStatusDate;
    }

    /**
     * Sets the value of the markCurrentStatusDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setMarkCurrentStatusDate(XMLGregorianCalendar value) {
        this.markCurrentStatusDate = value;
    }

    /**
     * Gets the value of the designatedCountryDetails property.
     * 
     * @return
     *     possible object is
     *     {@link TradeMarkType.DesignatedCountryDetails }
     *     
     */
    public TradeMarkType.DesignatedCountryDetails getDesignatedCountryDetails() {
        return designatedCountryDetails;
    }

    /**
     * Sets the value of the designatedCountryDetails property.
     * 
     * @param value
     *     allowed object is
     *     {@link TradeMarkType.DesignatedCountryDetails }
     *     
     */
    public void setDesignatedCountryDetails(TradeMarkType.DesignatedCountryDetails value) {
        this.designatedCountryDetails = value;
    }

    /**
     * Gets the value of the kindMark property.
     * 
     * @return
     *     possible object is
     *     {@link KindMarkType }
     *     
     */
    public KindMarkType getKindMark() {
        return kindMark;
    }

    /**
     * Sets the value of the kindMark property.
     * 
     * @param value
     *     allowed object is
     *     {@link KindMarkType }
     *     
     */
    public void setKindMark(KindMarkType value) {
        this.kindMark = value;
    }

    /**
     * Gets the value of the markFeature property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMarkFeature() {
        return markFeature;
    }

    /**
     * Sets the value of the markFeature property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMarkFeature(String value) {
        this.markFeature = value;
    }

    /**
     * Gets the value of the markDescriptionDetails property.
     * 
     * @return
     *     possible object is
     *     {@link TradeMarkType.MarkDescriptionDetails }
     *     
     */
    public TradeMarkType.MarkDescriptionDetails getMarkDescriptionDetails() {
        return markDescriptionDetails;
    }

    /**
     * Sets the value of the markDescriptionDetails property.
     * 
     * @param value
     *     allowed object is
     *     {@link TradeMarkType.MarkDescriptionDetails }
     *     
     */
    public void setMarkDescriptionDetails(TradeMarkType.MarkDescriptionDetails value) {
        this.markDescriptionDetails = value;
    }

    /**
     * Gets the value of the markDisclaimerDetails property.
     * 
     * @return
     *     possible object is
     *     {@link TradeMarkType.MarkDisclaimerDetails }
     *     
     */
    public TradeMarkType.MarkDisclaimerDetails getMarkDisclaimerDetails() {
        return markDisclaimerDetails;
    }

    /**
     * Sets the value of the markDisclaimerDetails property.
     * 
     * @param value
     *     allowed object is
     *     {@link TradeMarkType.MarkDisclaimerDetails }
     *     
     */
    public void setMarkDisclaimerDetails(TradeMarkType.MarkDisclaimerDetails value) {
        this.markDisclaimerDetails = value;
    }

    /**
     * Gets the value of the specialCircumstanceText property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSpecialCircumstanceText() {
        return specialCircumstanceText;
    }

    /**
     * Sets the value of the specialCircumstanceText property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSpecialCircumstanceText(String value) {
        this.specialCircumstanceText = value;
    }

    /**
     * Gets the value of the totalMarkSeries property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getTotalMarkSeries() {
        return totalMarkSeries;
    }

    /**
     * Sets the value of the totalMarkSeries property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setTotalMarkSeries(BigInteger value) {
        this.totalMarkSeries = value;
    }

    /**
     * Gets the value of the tradeDistinctivenessIndicator property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isTradeDistinctivenessIndicator() {
        return tradeDistinctivenessIndicator;
    }

    /**
     * Sets the value of the tradeDistinctivenessIndicator property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setTradeDistinctivenessIndicator(Boolean value) {
        this.tradeDistinctivenessIndicator = value;
    }

    /**
     * Gets the value of the tradeDistinctivenessText property.
     * 
     * @return
     *     possible object is
     *     {@link TextType }
     *     
     */
    public TextType getTradeDistinctivenessText() {
        return tradeDistinctivenessText;
    }

    /**
     * Sets the value of the tradeDistinctivenessText property.
     * 
     * @param value
     *     allowed object is
     *     {@link TextType }
     *     
     */
    public void setTradeDistinctivenessText(TextType value) {
        this.tradeDistinctivenessText = value;
    }

    /**
     * Gets the value of the comment property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getComment() {
        return comment;
    }

    /**
     * Sets the value of the comment property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setComment(String value) {
        this.comment = value;
    }

    /**
     * Gets the value of the oppositionPeriodStartDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getOppositionPeriodStartDate() {
        return oppositionPeriodStartDate;
    }

    /**
     * Sets the value of the oppositionPeriodStartDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setOppositionPeriodStartDate(XMLGregorianCalendar value) {
        this.oppositionPeriodStartDate = value;
    }

    /**
     * Gets the value of the oppositionPeriodEndDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getOppositionPeriodEndDate() {
        return oppositionPeriodEndDate;
    }

    /**
     * Sets the value of the oppositionPeriodEndDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setOppositionPeriodEndDate(XMLGregorianCalendar value) {
        this.oppositionPeriodEndDate = value;
    }

    /**
     * Gets the value of the wordMarkSpecification property.
     * 
     * @return
     *     possible object is
     *     {@link WordMarkSpecificationType }
     *     
     */
    public WordMarkSpecificationType getWordMarkSpecification() {
        return wordMarkSpecification;
    }

    /**
     * Sets the value of the wordMarkSpecification property.
     * 
     * @param value
     *     allowed object is
     *     {@link WordMarkSpecificationType }
     *     
     */
    public void setWordMarkSpecification(WordMarkSpecificationType value) {
        this.wordMarkSpecification = value;
    }

    /**
     * Gets the value of the markImageDetails property.
     * 
     * @return
     *     possible object is
     *     {@link TradeMarkType.MarkImageDetails }
     *     
     */
    public TradeMarkType.MarkImageDetails getMarkImageDetails() {
        return markImageDetails;
    }

    /**
     * Sets the value of the markImageDetails property.
     * 
     * @param value
     *     allowed object is
     *     {@link TradeMarkType.MarkImageDetails }
     *     
     */
    public void setMarkImageDetails(TradeMarkType.MarkImageDetails value) {
        this.markImageDetails = value;
    }

    /**
     * Gets the value of the goodsServicesDetails property.
     * 
     * @return
     *     possible object is
     *     {@link TradeMarkType.GoodsServicesDetails }
     *     
     */
    public TradeMarkType.GoodsServicesDetails getGoodsServicesDetails() {
        return goodsServicesDetails;
    }

    /**
     * Sets the value of the goodsServicesDetails property.
     * 
     * @param value
     *     allowed object is
     *     {@link TradeMarkType.GoodsServicesDetails }
     *     
     */
    public void setGoodsServicesDetails(TradeMarkType.GoodsServicesDetails value) {
        this.goodsServicesDetails = value;
    }

    /**
     * Gets the value of the priorityDetails property.
     * 
     * @return
     *     possible object is
     *     {@link TradeMarkType.PriorityDetails }
     *     
     */
    public TradeMarkType.PriorityDetails getPriorityDetails() {
        return priorityDetails;
    }

    /**
     * Sets the value of the priorityDetails property.
     * 
     * @param value
     *     allowed object is
     *     {@link TradeMarkType.PriorityDetails }
     *     
     */
    public void setPriorityDetails(TradeMarkType.PriorityDetails value) {
        this.priorityDetails = value;
    }

    /**
     * Gets the value of the exhibitionPriorityDetails property.
     * 
     * @return
     *     possible object is
     *     {@link TradeMarkType.ExhibitionPriorityDetails }
     *     
     */
    public TradeMarkType.ExhibitionPriorityDetails getExhibitionPriorityDetails() {
        return exhibitionPriorityDetails;
    }

    /**
     * Sets the value of the exhibitionPriorityDetails property.
     * 
     * @param value
     *     allowed object is
     *     {@link TradeMarkType.ExhibitionPriorityDetails }
     *     
     */
    public void setExhibitionPriorityDetails(TradeMarkType.ExhibitionPriorityDetails value) {
        this.exhibitionPriorityDetails = value;
    }

    /**
     * Gets the value of the publicationDetails property.
     * 
     * @return
     *     possible object is
     *     {@link TradeMarkType.PublicationDetails }
     *     
     */
    public TradeMarkType.PublicationDetails getPublicationDetails() {
        return publicationDetails;
    }

    /**
     * Sets the value of the publicationDetails property.
     * 
     * @param value
     *     allowed object is
     *     {@link TradeMarkType.PublicationDetails }
     *     
     */
    public void setPublicationDetails(TradeMarkType.PublicationDetails value) {
        this.publicationDetails = value;
    }

    /**
     * Gets the value of the applicantDetails property.
     * 
     * @return
     *     possible object is
     *     {@link TradeMarkType.ApplicantDetails }
     *     
     */
    public TradeMarkType.ApplicantDetails getApplicantDetails() {
        return applicantDetails;
    }

    /**
     * Sets the value of the applicantDetails property.
     * 
     * @param value
     *     allowed object is
     *     {@link TradeMarkType.ApplicantDetails }
     *     
     */
    public void setApplicantDetails(TradeMarkType.ApplicantDetails value) {
        this.applicantDetails = value;
    }

    /**
     * Gets the value of the representativeDetails property.
     * 
     * @return
     *     possible object is
     *     {@link TradeMarkType.RepresentativeDetails }
     *     
     */
    public TradeMarkType.RepresentativeDetails getRepresentativeDetails() {
        return representativeDetails;
    }

    /**
     * Sets the value of the representativeDetails property.
     * 
     * @param value
     *     allowed object is
     *     {@link TradeMarkType.RepresentativeDetails }
     *     
     */
    public void setRepresentativeDetails(TradeMarkType.RepresentativeDetails value) {
        this.representativeDetails = value;
    }

    /**
     * Gets the value of the correspondenceAddress property.
     * 
     * @return
     *     possible object is
     *     {@link CorrespondenceAddressType }
     *     
     */
    public CorrespondenceAddressType getCorrespondenceAddress() {
        return correspondenceAddress;
    }

    /**
     * Sets the value of the correspondenceAddress property.
     * 
     * @param value
     *     allowed object is
     *     {@link CorrespondenceAddressType }
     *     
     */
    public void setCorrespondenceAddress(CorrespondenceAddressType value) {
        this.correspondenceAddress = value;
    }

    /**
     * Gets the value of the oppositionDetails property.
     * 
     * @return
     *     possible object is
     *     {@link TradeMarkType.OppositionDetails }
     *     
     */
    public TradeMarkType.OppositionDetails getOppositionDetails() {
        return oppositionDetails;
    }

    /**
     * Sets the value of the oppositionDetails property.
     * 
     * @param value
     *     allowed object is
     *     {@link TradeMarkType.OppositionDetails }
     *     
     */
    public void setOppositionDetails(TradeMarkType.OppositionDetails value) {
        this.oppositionDetails = value;
    }

    /**
     * Gets the value of the markRecordDetails property.
     * 
     * @return
     *     possible object is
     *     {@link TradeMarkType.MarkRecordDetails }
     *     
     */
    public TradeMarkType.MarkRecordDetails getMarkRecordDetails() {
        return markRecordDetails;
    }

    /**
     * Sets the value of the markRecordDetails property.
     * 
     * @param value
     *     allowed object is
     *     {@link TradeMarkType.MarkRecordDetails }
     *     
     */
    public void setMarkRecordDetails(TradeMarkType.MarkRecordDetails value) {
        this.markRecordDetails = value;
    }

    /**
     * Gets the value of the markEventDetails property.
     * 
     * @return
     *     possible object is
     *     {@link TradeMarkType.MarkEventDetails }
     *     
     */
    public TradeMarkType.MarkEventDetails getMarkEventDetails() {
        return markEventDetails;
    }

    /**
     * Sets the value of the markEventDetails property.
     * 
     * @param value
     *     allowed object is
     *     {@link TradeMarkType.MarkEventDetails }
     *     
     */
    public void setMarkEventDetails(TradeMarkType.MarkEventDetails value) {
        this.markEventDetails = value;
    }

    /**
     * Gets the value of the appealDetails property.
     * 
     * @return
     *     possible object is
     *     {@link TradeMarkType.AppealDetails }
     *     
     */
    public TradeMarkType.AppealDetails getAppealDetails() {
        return appealDetails;
    }

    /**
     * Sets the value of the appealDetails property.
     * 
     * @param value
     *     allowed object is
     *     {@link TradeMarkType.AppealDetails }
     *     
     */
    public void setAppealDetails(TradeMarkType.AppealDetails value) {
        this.appealDetails = value;
    }

    /**
     * Gets the value of the operationCode property.
     * 
     * @return
     *     possible object is
     *     {@link OperationCodeType }
     *     
     */
    public OperationCodeType getOperationCode() {
        return operationCode;
    }

    /**
     * Sets the value of the operationCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link OperationCodeType }
     *     
     */
    public void setOperationCode(OperationCodeType value) {
        this.operationCode = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="Appeal" type="{http://www.oami.europa.eu/TM-Search}AppealType" maxOccurs="unbounded"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "appeal"
    })
    public static class AppealDetails {

        @XmlElement(name = "Appeal", required = true)
        protected List<AppealType> appeal;

        /**
         * Gets the value of the appeal property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the appeal property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getAppeal().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link AppealType }
         * 
         * 
         */
        public List<AppealType> getAppeal() {
            if (appeal == null) {
                appeal = new ArrayList<AppealType>();
            }
            return this.appeal;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="Applicant" type="{http://www.oami.europa.eu/TM-Search}ApplicantType" maxOccurs="unbounded"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "applicant"
    })
    public static class ApplicantDetails {

        @XmlElement(name = "Applicant", required = true)
        protected List<ApplicantType> applicant;

        /**
         * Gets the value of the applicant property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the applicant property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getApplicant().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link ApplicantType }
         * 
         * 
         */
        public List<ApplicantType> getApplicant() {
            if (applicant == null) {
                applicant = new ArrayList<ApplicantType>();
            }
            return this.applicant;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="DesignatedCountry" type="{http://www.oami.europa.eu/TM-Search}DesignatedCountryType" maxOccurs="unbounded"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "designatedCountry"
    })
    public static class DesignatedCountryDetails {

        @XmlElement(name = "DesignatedCountry", required = true)
        protected List<DesignatedCountryType> designatedCountry;

        /**
         * Gets the value of the designatedCountry property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the designatedCountry property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getDesignatedCountry().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link DesignatedCountryType }
         * 
         * 
         */
        public List<DesignatedCountryType> getDesignatedCountry() {
            if (designatedCountry == null) {
                designatedCountry = new ArrayList<DesignatedCountryType>();
            }
            return this.designatedCountry;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="ExhibitionPriority" type="{http://www.oami.europa.eu/TM-Search}ExhibitionPriorityType" maxOccurs="unbounded"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "exhibitionPriority"
    })
    public static class ExhibitionPriorityDetails {

        @XmlElement(name = "ExhibitionPriority", required = true)
        protected List<ExhibitionPriorityType> exhibitionPriority;

        /**
         * Gets the value of the exhibitionPriority property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the exhibitionPriority property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getExhibitionPriority().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link ExhibitionPriorityType }
         * 
         * 
         */
        public List<ExhibitionPriorityType> getExhibitionPriority() {
            if (exhibitionPriority == null) {
                exhibitionPriority = new ArrayList<ExhibitionPriorityType>();
            }
            return this.exhibitionPriority;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="GoodsServices" type="{http://www.oami.europa.eu/TM-Search}GoodsServicesType"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "goodsServices"
    })
    public static class GoodsServicesDetails {

        @XmlElement(name = "GoodsServices", required = true)
        protected GoodsServicesType goodsServices;

        /**
         * Gets the value of the goodsServices property.
         * 
         * @return
         *     possible object is
         *     {@link GoodsServicesType }
         *     
         */
        public GoodsServicesType getGoodsServices() {
            return goodsServices;
        }

        /**
         * Sets the value of the goodsServices property.
         * 
         * @param value
         *     allowed object is
         *     {@link GoodsServicesType }
         *     
         */
        public void setGoodsServices(GoodsServicesType value) {
            this.goodsServices = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="MarkDescription" type="{http://www.oami.europa.eu/TM-Search}TextType" maxOccurs="unbounded"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "markDescription"
    })
    public static class MarkDescriptionDetails {

        @XmlElement(name = "MarkDescription", required = true)
        protected List<TextType> markDescription;

        /**
         * Gets the value of the markDescription property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the markDescription property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getMarkDescription().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link TextType }
         * 
         * 
         */
        public List<TextType> getMarkDescription() {
            if (markDescription == null) {
                markDescription = new ArrayList<TextType>();
            }
            return this.markDescription;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="MarkDisclaimer" type="{http://www.oami.europa.eu/TM-Search}TextType" maxOccurs="unbounded"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "markDisclaimer"
    })
    public static class MarkDisclaimerDetails {

        @XmlElement(name = "MarkDisclaimer", required = true)
        protected List<TextType> markDisclaimer;

        /**
         * Gets the value of the markDisclaimer property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the markDisclaimer property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getMarkDisclaimer().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link TextType }
         * 
         * 
         */
        public List<TextType> getMarkDisclaimer() {
            if (markDisclaimer == null) {
                markDisclaimer = new ArrayList<TextType>();
            }
            return this.markDisclaimer;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="MarkEvent" type="{http://www.oami.europa.eu/TM-Search}MarkEventType" maxOccurs="unbounded"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "markEvent"
    })
    public static class MarkEventDetails {

        @XmlElement(name = "MarkEvent", required = true)
        protected List<MarkEventType> markEvent;

        /**
         * Gets the value of the markEvent property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the markEvent property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getMarkEvent().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link MarkEventType }
         * 
         * 
         */
        public List<MarkEventType> getMarkEvent() {
            if (markEvent == null) {
                markEvent = new ArrayList<MarkEventType>();
            }
            return this.markEvent;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="MarkImage" type="{http://www.oami.europa.eu/TM-Search}MarkImageType" maxOccurs="unbounded"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "markImage"
    })
    public static class MarkImageDetails {

        @XmlElement(name = "MarkImage", required = true)
        protected List<MarkImageType> markImage;

        /**
         * Gets the value of the markImage property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the markImage property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getMarkImage().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link MarkImageType }
         * 
         * 
         */
        public List<MarkImageType> getMarkImage() {
            if (markImage == null) {
                markImage = new ArrayList<MarkImageType>();
            }
            return this.markImage;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="MarkRecord" type="{http://www.oami.europa.eu/TM-Search}MarkRecordType" maxOccurs="unbounded"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "markRecord"
    })
    public static class MarkRecordDetails {

        @XmlElement(name = "MarkRecord", required = true)
        protected List<MarkRecordType> markRecord;

        /**
         * Gets the value of the markRecord property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the markRecord property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getMarkRecord().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link MarkRecordType }
         * 
         * 
         */
        public List<MarkRecordType> getMarkRecord() {
            if (markRecord == null) {
                markRecord = new ArrayList<MarkRecordType>();
            }
            return this.markRecord;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="Opposition" type="{http://www.oami.europa.eu/TM-Search}OppositionType" maxOccurs="unbounded"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "opposition"
    })
    public static class OppositionDetails {

        @XmlElement(name = "Opposition", required = true)
        protected List<OppositionType> opposition;

        /**
         * Gets the value of the opposition property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the opposition property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getOpposition().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link OppositionType }
         * 
         * 
         */
        public List<OppositionType> getOpposition() {
            if (opposition == null) {
                opposition = new ArrayList<OppositionType>();
            }
            return this.opposition;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="Priority" type="{http://www.oami.europa.eu/TM-Search}PriorityType" maxOccurs="unbounded"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "priority"
    })
    public static class PriorityDetails {

        @XmlElement(name = "Priority", required = true)
        protected List<PriorityType> priority;

        /**
         * Gets the value of the priority property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the priority property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getPriority().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link PriorityType }
         * 
         * 
         */
        public List<PriorityType> getPriority() {
            if (priority == null) {
                priority = new ArrayList<PriorityType>();
            }
            return this.priority;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="Publication" type="{http://www.oami.europa.eu/TM-Search}PublicationType" maxOccurs="unbounded"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "publication"
    })
    public static class PublicationDetails {

        @XmlElement(name = "Publication", required = true)
        protected List<PublicationType> publication;

        /**
         * Gets the value of the publication property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the publication property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getPublication().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link PublicationType }
         * 
         * 
         */
        public List<PublicationType> getPublication() {
            if (publication == null) {
                publication = new ArrayList<PublicationType>();
            }
            return this.publication;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="Representative" type="{http://www.oami.europa.eu/TM-Search}RepresentativeType" maxOccurs="unbounded"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "representative"
    })
    public static class RepresentativeDetails {

        @XmlElement(name = "Representative", required = true)
        protected List<RepresentativeType> representative;

        /**
         * Gets the value of the representative property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the representative property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getRepresentative().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link RepresentativeType }
         * 
         * 
         */
        public List<RepresentativeType> getRepresentative() {
            if (representative == null) {
                representative = new ArrayList<RepresentativeType>();
            }
            return this.representative;
        }

    }

}
