//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.03.11 at 12:27:12 AM CET 
//


package jxml;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for TransactionErrorType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="TransactionErrorType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="TransactionErrorCode" type="{http://www.oami.europa.eu/TM-Search}TransactionErrorCodeType"/>
 *         &lt;element name="TransactionErrorText" type="{http://www.w3.org/2001/XMLSchema}token" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TransactionErrorType", propOrder = {
    "transactionErrorCode",
    "transactionErrorText"
})
public class TransactionErrorType {

    @XmlElement(name = "TransactionErrorCode", required = true)
    @XmlSchemaType(name = "token")
    protected TransactionErrorCodeType transactionErrorCode;
    @XmlElement(name = "TransactionErrorText")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "token")
    protected String transactionErrorText;

    /**
     * Gets the value of the transactionErrorCode property.
     * 
     * @return
     *     possible object is
     *     {@link TransactionErrorCodeType }
     *     
     */
    public TransactionErrorCodeType getTransactionErrorCode() {
        return transactionErrorCode;
    }

    /**
     * Sets the value of the transactionErrorCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link TransactionErrorCodeType }
     *     
     */
    public void setTransactionErrorCode(TransactionErrorCodeType value) {
        this.transactionErrorCode = value;
    }

    /**
     * Gets the value of the transactionErrorText property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTransactionErrorText() {
        return transactionErrorText;
    }

    /**
     * Sets the value of the transactionErrorText property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTransactionErrorText(String value) {
        this.transactionErrorText = value;
    }

}
