//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.03.11 at 12:27:12 AM CET 
//


package jxml;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for TransactionType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="TransactionType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="TransactionHeader" type="{http://www.oami.europa.eu/TM-Search}TransactionHeaderType" minOccurs="0"/>
 *         &lt;element name="TradeMarkTransactionBody" type="{http://www.oami.europa.eu/TM-Search}TransactionBodyType"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TransactionType", propOrder = {
    "transactionHeader",
    "tradeMarkTransactionBody"
})
@XmlRootElement(name="Transaction", namespace="http://www.oami.europa.eu/TM-Search")
public class TransactionType {

    @XmlElement(name = "TransactionHeader")
    protected TransactionHeaderType transactionHeader;
    @XmlElement(name = "TradeMarkTransactionBody", required = true)
    protected TransactionBodyType tradeMarkTransactionBody;

    /**
     * Gets the value of the transactionHeader property.
     * 
     * @return
     *     possible object is
     *     {@link TransactionHeaderType }
     *     
     */
    public TransactionHeaderType getTransactionHeader() {
        return transactionHeader;
    }

    /**
     * Sets the value of the transactionHeader property.
     * 
     * @param value
     *     allowed object is
     *     {@link TransactionHeaderType }
     *     
     */
    public void setTransactionHeader(TransactionHeaderType value) {
        this.transactionHeader = value;
    }

    /**
     * Gets the value of the tradeMarkTransactionBody property.
     * 
     * @return
     *     possible object is
     *     {@link TransactionBodyType }
     *     
     */
    public TransactionBodyType getTradeMarkTransactionBody() {
        return tradeMarkTransactionBody;
    }

    /**
     * Sets the value of the tradeMarkTransactionBody property.
     * 
     * @param value
     *     allowed object is
     *     {@link TransactionBodyType }
     *     
     */
    public void setTradeMarkTransactionBody(TransactionBodyType value) {
        this.tradeMarkTransactionBody = value;
    }

}
