//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.03.11 at 12:27:12 AM CET 
//


package jxml;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for WIPOST3CodeType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="WIPOST3CodeType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}NMTOKEN">
 *     &lt;enumeration value="AD"/>
 *     &lt;enumeration value="AE"/>
 *     &lt;enumeration value="AF"/>
 *     &lt;enumeration value="AG"/>
 *     &lt;enumeration value="AI"/>
 *     &lt;enumeration value="AL"/>
 *     &lt;enumeration value="AM"/>
 *     &lt;enumeration value="AN"/>
 *     &lt;enumeration value="AO"/>
 *     &lt;enumeration value="AP"/>
 *     &lt;enumeration value="AR"/>
 *     &lt;enumeration value="AT"/>
 *     &lt;enumeration value="AU"/>
 *     &lt;enumeration value="AW"/>
 *     &lt;enumeration value="AZ"/>
 *     &lt;enumeration value="BA"/>
 *     &lt;enumeration value="BB"/>
 *     &lt;enumeration value="BD"/>
 *     &lt;enumeration value="BE"/>
 *     &lt;enumeration value="BF"/>
 *     &lt;enumeration value="BG"/>
 *     &lt;enumeration value="BH"/>
 *     &lt;enumeration value="BI"/>
 *     &lt;enumeration value="BJ"/>
 *     &lt;enumeration value="BM"/>
 *     &lt;enumeration value="BN"/>
 *     &lt;enumeration value="BO"/>
 *     &lt;enumeration value="BQ"/>
 *     &lt;enumeration value="BR"/>
 *     &lt;enumeration value="BS"/>
 *     &lt;enumeration value="BT"/>
 *     &lt;enumeration value="BV"/>
 *     &lt;enumeration value="BW"/>
 *     &lt;enumeration value="BX"/>
 *     &lt;enumeration value="BY"/>
 *     &lt;enumeration value="BZ"/>
 *     &lt;enumeration value="CA"/>
 *     &lt;enumeration value="CD"/>
 *     &lt;enumeration value="CF"/>
 *     &lt;enumeration value="CG"/>
 *     &lt;enumeration value="CH"/>
 *     &lt;enumeration value="CI"/>
 *     &lt;enumeration value="CK"/>
 *     &lt;enumeration value="CL"/>
 *     &lt;enumeration value="CM"/>
 *     &lt;enumeration value="CN"/>
 *     &lt;enumeration value="CO"/>
 *     &lt;enumeration value="CR"/>
 *     &lt;enumeration value="CU"/>
 *     &lt;enumeration value="CV"/>
 *     &lt;enumeration value="CW"/>
 *     &lt;enumeration value="CY"/>
 *     &lt;enumeration value="CZ"/>
 *     &lt;enumeration value="DE"/>
 *     &lt;enumeration value="DJ"/>
 *     &lt;enumeration value="DK"/>
 *     &lt;enumeration value="DM"/>
 *     &lt;enumeration value="DO"/>
 *     &lt;enumeration value="DZ"/>
 *     &lt;enumeration value="EA"/>
 *     &lt;enumeration value="EC"/>
 *     &lt;enumeration value="EE"/>
 *     &lt;enumeration value="EG"/>
 *     &lt;enumeration value="EH"/>
 *     &lt;enumeration value="EM"/>
 *     &lt;enumeration value="EP"/>
 *     &lt;enumeration value="ER"/>
 *     &lt;enumeration value="ES"/>
 *     &lt;enumeration value="ET"/>
 *     &lt;enumeration value="FI"/>
 *     &lt;enumeration value="FJ"/>
 *     &lt;enumeration value="FK"/>
 *     &lt;enumeration value="FO"/>
 *     &lt;enumeration value="FR"/>
 *     &lt;enumeration value="GA"/>
 *     &lt;enumeration value="GB"/>
 *     &lt;enumeration value="GC"/>
 *     &lt;enumeration value="GD"/>
 *     &lt;enumeration value="GE"/>
 *     &lt;enumeration value="GG"/>
 *     &lt;enumeration value="GH"/>
 *     &lt;enumeration value="GI"/>
 *     &lt;enumeration value="GL"/>
 *     &lt;enumeration value="GM"/>
 *     &lt;enumeration value="GN"/>
 *     &lt;enumeration value="GQ"/>
 *     &lt;enumeration value="GR"/>
 *     &lt;enumeration value="GS"/>
 *     &lt;enumeration value="GT"/>
 *     &lt;enumeration value="GW"/>
 *     &lt;enumeration value="GY"/>
 *     &lt;enumeration value="HK"/>
 *     &lt;enumeration value="HN"/>
 *     &lt;enumeration value="HR"/>
 *     &lt;enumeration value="HT"/>
 *     &lt;enumeration value="HU"/>
 *     &lt;enumeration value="IB"/>
 *     &lt;enumeration value="ID"/>
 *     &lt;enumeration value="IE"/>
 *     &lt;enumeration value="IL"/>
 *     &lt;enumeration value="IM"/>
 *     &lt;enumeration value="IN"/>
 *     &lt;enumeration value="IQ"/>
 *     &lt;enumeration value="IR"/>
 *     &lt;enumeration value="IS"/>
 *     &lt;enumeration value="IT"/>
 *     &lt;enumeration value="JE"/>
 *     &lt;enumeration value="JM"/>
 *     &lt;enumeration value="JO"/>
 *     &lt;enumeration value="JP"/>
 *     &lt;enumeration value="KE"/>
 *     &lt;enumeration value="KG"/>
 *     &lt;enumeration value="KH"/>
 *     &lt;enumeration value="KI"/>
 *     &lt;enumeration value="KM"/>
 *     &lt;enumeration value="KN"/>
 *     &lt;enumeration value="KP"/>
 *     &lt;enumeration value="KR"/>
 *     &lt;enumeration value="KW"/>
 *     &lt;enumeration value="KY"/>
 *     &lt;enumeration value="KZ"/>
 *     &lt;enumeration value="LA"/>
 *     &lt;enumeration value="LB"/>
 *     &lt;enumeration value="LC"/>
 *     &lt;enumeration value="LI"/>
 *     &lt;enumeration value="LK"/>
 *     &lt;enumeration value="LR"/>
 *     &lt;enumeration value="LS"/>
 *     &lt;enumeration value="LT"/>
 *     &lt;enumeration value="LU"/>
 *     &lt;enumeration value="LV"/>
 *     &lt;enumeration value="LY"/>
 *     &lt;enumeration value="MA"/>
 *     &lt;enumeration value="MC"/>
 *     &lt;enumeration value="MD"/>
 *     &lt;enumeration value="ME"/>
 *     &lt;enumeration value="MG"/>
 *     &lt;enumeration value="MK"/>
 *     &lt;enumeration value="ML"/>
 *     &lt;enumeration value="MM"/>
 *     &lt;enumeration value="MN"/>
 *     &lt;enumeration value="MO"/>
 *     &lt;enumeration value="MP"/>
 *     &lt;enumeration value="MR"/>
 *     &lt;enumeration value="MS"/>
 *     &lt;enumeration value="MT"/>
 *     &lt;enumeration value="MU"/>
 *     &lt;enumeration value="MV"/>
 *     &lt;enumeration value="MW"/>
 *     &lt;enumeration value="MX"/>
 *     &lt;enumeration value="MY"/>
 *     &lt;enumeration value="MZ"/>
 *     &lt;enumeration value="NA"/>
 *     &lt;enumeration value="NE"/>
 *     &lt;enumeration value="NG"/>
 *     &lt;enumeration value="NI"/>
 *     &lt;enumeration value="NL"/>
 *     &lt;enumeration value="NO"/>
 *     &lt;enumeration value="NP"/>
 *     &lt;enumeration value="NR"/>
 *     &lt;enumeration value="NZ"/>
 *     &lt;enumeration value="OA"/>
 *     &lt;enumeration value="OM"/>
 *     &lt;enumeration value="PA"/>
 *     &lt;enumeration value="PE"/>
 *     &lt;enumeration value="PG"/>
 *     &lt;enumeration value="PH"/>
 *     &lt;enumeration value="PK"/>
 *     &lt;enumeration value="PL"/>
 *     &lt;enumeration value="PT"/>
 *     &lt;enumeration value="PW"/>
 *     &lt;enumeration value="PY"/>
 *     &lt;enumeration value="QA"/>
 *     &lt;enumeration value="QZ"/>
 *     &lt;enumeration value="RO"/>
 *     &lt;enumeration value="RS"/>
 *     &lt;enumeration value="RU"/>
 *     &lt;enumeration value="RW"/>
 *     &lt;enumeration value="SA"/>
 *     &lt;enumeration value="SB"/>
 *     &lt;enumeration value="SC"/>
 *     &lt;enumeration value="SD"/>
 *     &lt;enumeration value="SE"/>
 *     &lt;enumeration value="SG"/>
 *     &lt;enumeration value="SH"/>
 *     &lt;enumeration value="SI"/>
 *     &lt;enumeration value="SK"/>
 *     &lt;enumeration value="SL"/>
 *     &lt;enumeration value="SM"/>
 *     &lt;enumeration value="SN"/>
 *     &lt;enumeration value="SO"/>
 *     &lt;enumeration value="SR"/>
 *     &lt;enumeration value="SS"/>
 *     &lt;enumeration value="ST"/>
 *     &lt;enumeration value="SV"/>
 *     &lt;enumeration value="SX"/>
 *     &lt;enumeration value="SY"/>
 *     &lt;enumeration value="SZ"/>
 *     &lt;enumeration value="TC"/>
 *     &lt;enumeration value="TD"/>
 *     &lt;enumeration value="TG"/>
 *     &lt;enumeration value="TH"/>
 *     &lt;enumeration value="TJ"/>
 *     &lt;enumeration value="TL"/>
 *     &lt;enumeration value="TM"/>
 *     &lt;enumeration value="TN"/>
 *     &lt;enumeration value="TO"/>
 *     &lt;enumeration value="TR"/>
 *     &lt;enumeration value="TT"/>
 *     &lt;enumeration value="TV"/>
 *     &lt;enumeration value="TW"/>
 *     &lt;enumeration value="TZ"/>
 *     &lt;enumeration value="UA"/>
 *     &lt;enumeration value="UG"/>
 *     &lt;enumeration value="US"/>
 *     &lt;enumeration value="UY"/>
 *     &lt;enumeration value="UZ"/>
 *     &lt;enumeration value="VA"/>
 *     &lt;enumeration value="VC"/>
 *     &lt;enumeration value="VE"/>
 *     &lt;enumeration value="VG"/>
 *     &lt;enumeration value="VN"/>
 *     &lt;enumeration value="VU"/>
 *     &lt;enumeration value="WO"/>
 *     &lt;enumeration value="WS"/>
 *     &lt;enumeration value="XN"/>
 *     &lt;enumeration value="YE"/>
 *     &lt;enumeration value="ZA"/>
 *     &lt;enumeration value="ZM"/>
 *     &lt;enumeration value="ZW"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "WIPOST3CodeType")
@XmlEnum
public enum WIPOST3CodeType {


    /**
     * Andorra
     * 
     */
    AD,

    /**
     * United Arab Emirates
     * 
     */
    AE,

    /**
     * Afghanistan
     * 
     */
    AF,

    /**
     * Antigua And Barbuda
     * 
     */
    AG,

    /**
     * Anguilla
     * 
     */
    AI,

    /**
     * Albania
     * 
     */
    AL,

    /**
     * Armenia
     * 
     */
    AM,

    /**
     * Netherlands Antilles
     * 
     */
    AN,

    /**
     * Angola
     * 
     */
    AO,

    /**
     * African Regional Industrial Property Organization (ARIPO)
     * 
     */
    AP,

    /**
     * Argentina
     * 
     */
    AR,

    /**
     * Austria
     * 
     */
    AT,

    /**
     * Australia
     * 
     */
    AU,

    /**
     * Aruba
     * 
     */
    AW,

    /**
     * Azerbaijan
     * 
     */
    AZ,

    /**
     * Bosnia and Herzegovina
     * 
     */
    BA,

    /**
     * Barbados
     * 
     */
    BB,

    /**
     * Bangladesh
     * 
     */
    BD,

    /**
     * Belgium
     * 
     */
    BE,

    /**
     * Burkina Faso
     * 
     */
    BF,

    /**
     * Bulgaria
     * 
     */
    BG,

    /**
     * Bahrain
     * 
     */
    BH,

    /**
     * Burundi
     * 
     */
    BI,

    /**
     * Benin
     * 
     */
    BJ,

    /**
     * Bermuda
     * 
     */
    BM,

    /**
     * Brunei Darussalam
     * 
     */
    BN,

    /**
     * Plurinational State of Bolivia
     * 
     */
    BO,

    /**
     * Bonaire, Sint Eustatius and Saba
     * 
     */
    BQ,

    /**
     * Brazil
     * 
     */
    BR,

    /**
     * Bahamas
     * 
     */
    BS,

    /**
     * Bhutan
     * 
     */
    BT,

    /**
     * Bouvet Island
     * 
     */
    BV,

    /**
     * Botswana
     * 
     */
    BW,

    /**
     * Benelux Office for Intellectual Property (BOIP)
     * 
     */
    BX,

    /**
     * Belarus
     * 
     */
    BY,

    /**
     * Belize
     * 
     */
    BZ,

    /**
     * Canada
     * 
     */
    CA,

    /**
     * Democratic Republic of the Congo
     * 
     */
    CD,

    /**
     * Central African Republic
     * 
     */
    CF,

    /**
     * Congo
     * 
     */
    CG,

    /**
     * Switzerland
     * 
     */
    CH,

    /**
     * Cote D'Ivoire
     * 
     */
    CI,

    /**
     * Cook Islands
     * 
     */
    CK,

    /**
     * Chile
     * 
     */
    CL,

    /**
     * Cameroon
     * 
     */
    CM,

    /**
     * China
     * 
     */
    CN,

    /**
     * Colombia
     * 
     */
    CO,

    /**
     * Costa Rica
     * 
     */
    CR,

    /**
     * Cuba
     * 
     */
    CU,

    /**
     * Cape Verde
     * 
     */
    CV,

    /**
     * Curacao
     * 
     */
    CW,

    /**
     * Cyprus
     * 
     */
    CY,

    /**
     * Czech Republic
     * 
     */
    CZ,

    /**
     * Germany
     * 
     */
    DE,

    /**
     * Djibouti
     * 
     */
    DJ,

    /**
     * Denmark
     * 
     */
    DK,

    /**
     * Dominica
     * 
     */
    DM,

    /**
     * Dominican Republic
     * 
     */
    DO,

    /**
     * Algeria
     * 
     */
    DZ,

    /**
     * Eurasian Patent Organization (EAPO)
     * 
     */
    EA,

    /**
     * Ecuador
     * 
     */
    EC,

    /**
     * Estonia
     * 
     */
    EE,

    /**
     * Egypt
     * 
     */
    EG,

    /**
     * Western Sahara
     * 
     */
    EH,

    /**
     * Office for Harmonization in the Internal Market (Trademarks and Designs) (OHIM)
     * 
     */
    EM,

    /**
     * European Patent Office (EPO)
     * 
     */
    EP,

    /**
     * Eritrea
     * 
     */
    ER,

    /**
     * Spain
     * 
     */
    ES,

    /**
     * Ethiopia
     * 
     */
    ET,

    /**
     * Finland
     * 
     */
    FI,

    /**
     * Fiji
     * 
     */
    FJ,

    /**
     * Falkland Islands (Malvinas)
     * 
     */
    FK,

    /**
     * Faroe Islands
     * 
     */
    FO,

    /**
     * France
     * 
     */
    FR,

    /**
     * Gabon
     * 
     */
    GA,

    /**
     * United Kingdom
     * 
     */
    GB,

    /**
     * Patent Office of the Cooperation Council for the Arab States of the Gulf (GCC)
     * 
     */
    GC,

    /**
     * Grenada
     * 
     */
    GD,

    /**
     * Georgia
     * 
     */
    GE,

    /**
     * Guernsey
     * 
     */
    GG,

    /**
     * Ghana
     * 
     */
    GH,

    /**
     * Gibraltar
     * 
     */
    GI,

    /**
     * Greenland
     * 
     */
    GL,

    /**
     * Gambia
     * 
     */
    GM,

    /**
     * Guinea
     * 
     */
    GN,

    /**
     * Equatorial Guinea
     * 
     */
    GQ,

    /**
     * Greece
     * 
     */
    GR,

    /**
     * South Georgia and South Sandwich Islands
     * 
     */
    GS,

    /**
     * Guatemala
     * 
     */
    GT,

    /**
     * Guinea-Bissau
     * 
     */
    GW,

    /**
     * Guyana
     * 
     */
    GY,

    /**
     * The Hong Kong Special Administration Region of the People's Republic of China
     * 
     */
    HK,

    /**
     * Honduras
     * 
     */
    HN,

    /**
     * Croatia
     * 
     */
    HR,

    /**
     * Haiti
     * 
     */
    HT,

    /**
     * Hungary
     * 
     */
    HU,

    /**
     * International Bureau of the World Intellectual Property Organization (WIPO)
     * 
     */
    IB,

    /**
     * Indonesia
     * 
     */
    ID,

    /**
     * Ireland
     * 
     */
    IE,

    /**
     * Israel
     * 
     */
    IL,

    /**
     * Isle of Man
     * 
     */
    IM,

    /**
     * India
     * 
     */
    IN,

    /**
     * Iraq
     * 
     */
    IQ,

    /**
     * Iran (Islamic Republic of)
     * 
     */
    IR,

    /**
     * Iceland
     * 
     */
    IS,

    /**
     * Italy
     * 
     */
    IT,

    /**
     * Jersey
     * 
     */
    JE,

    /**
     * Jamaica
     * 
     */
    JM,

    /**
     * Jordan
     * 
     */
    JO,

    /**
     * Japan
     * 
     */
    JP,

    /**
     * Kenya
     * 
     */
    KE,

    /**
     * Kyrgyzstan
     * 
     */
    KG,

    /**
     * Cambodia
     * 
     */
    KH,

    /**
     * Kiribati
     * 
     */
    KI,

    /**
     * Comoros
     * 
     */
    KM,

    /**
     * Saint Kitts and Nevis
     * 
     */
    KN,

    /**
     * Democratic People's Republic of Korea
     * 
     */
    KP,

    /**
     * Republic of Korea
     * 
     */
    KR,

    /**
     * Kuwait
     * 
     */
    KW,

    /**
     * Cayman Islands
     * 
     */
    KY,

    /**
     * Kazakhstan
     * 
     */
    KZ,

    /**
     * Lao People's Democratic Republic
     * 
     */
    LA,

    /**
     * Lebanon
     * 
     */
    LB,

    /**
     * Saint Lucia
     * 
     */
    LC,

    /**
     * Liechtenstein
     * 
     */
    LI,

    /**
     * Sri Lanka
     * 
     */
    LK,

    /**
     * Liberia
     * 
     */
    LR,

    /**
     * Lesotho
     * 
     */
    LS,

    /**
     * Lithuania
     * 
     */
    LT,

    /**
     * Luxembourg
     * 
     */
    LU,

    /**
     * Latvia
     * 
     */
    LV,

    /**
     * Libyan Arab Jamahiriya
     * 
     */
    LY,

    /**
     * Morocco
     * 
     */
    MA,

    /**
     * Monaco
     * 
     */
    MC,

    /**
     * Republic of Moldova
     * 
     */
    MD,

    /**
     * Montenegro
     * 
     */
    ME,

    /**
     * Madagascar
     * 
     */
    MG,

    /**
     * The former Yugoslav Republic of Macedonia
     * 
     */
    MK,

    /**
     * Mali
     * 
     */
    ML,

    /**
     * Myanmar
     * 
     */
    MM,

    /**
     * Mongolia
     * 
     */
    MN,

    /**
     * Macau
     * 
     */
    MO,

    /**
     * Northern Mariana Islands
     * 
     */
    MP,

    /**
     * Mauritania
     * 
     */
    MR,

    /**
     * Montserrat
     * 
     */
    MS,

    /**
     * Malta
     * 
     */
    MT,

    /**
     * Mauritius
     * 
     */
    MU,

    /**
     * Maldives
     * 
     */
    MV,

    /**
     * Malawi
     * 
     */
    MW,

    /**
     * Mexico
     * 
     */
    MX,

    /**
     * Malaysia
     * 
     */
    MY,

    /**
     * Mozambique
     * 
     */
    MZ,

    /**
     * Namibia
     * 
     */
    NA,

    /**
     * Niger
     * 
     */
    NE,

    /**
     * Nigeria
     * 
     */
    NG,

    /**
     * Nicaragua
     * 
     */
    NI,

    /**
     * Netherlands
     * 
     */
    NL,

    /**
     * Norway
     * 
     */
    NO,

    /**
     * Nepal
     * 
     */
    NP,

    /**
     * Nauru
     * 
     */
    NR,

    /**
     * New Zealand
     * 
     */
    NZ,

    /**
     * African Intellectual Property Organization (OAPI)
     * 
     */
    OA,

    /**
     * Oman
     * 
     */
    OM,

    /**
     * Panama
     * 
     */
    PA,

    /**
     * Peru
     * 
     */
    PE,

    /**
     * Papua New Guinea
     * 
     */
    PG,

    /**
     * Philippines
     * 
     */
    PH,

    /**
     * Pakistan
     * 
     */
    PK,

    /**
     * Poland
     * 
     */
    PL,

    /**
     * Portugal
     * 
     */
    PT,

    /**
     * Palau
     * 
     */
    PW,

    /**
     * Paraguay
     * 
     */
    PY,

    /**
     * Qatar
     * 
     */
    QA,

    /**
     * Community Plant Variety Office (European Community) (CPVO)
     * 
     */
    QZ,

    /**
     * Romania
     * 
     */
    RO,

    /**
     * Serbia
     * 
     */
    RS,

    /**
     * Russian Federation
     * 
     */
    RU,

    /**
     * Rwanda
     * 
     */
    RW,

    /**
     * Saudi Arabia
     * 
     */
    SA,

    /**
     * Solomon Islands
     * 
     */
    SB,

    /**
     * Seychelles
     * 
     */
    SC,

    /**
     * Sudan
     * 
     */
    SD,

    /**
     * Sweden
     * 
     */
    SE,

    /**
     * Singapore
     * 
     */
    SG,

    /**
     * Saint Helena, Ascension and Tristan da Cunha
     * 
     */
    SH,

    /**
     * Slovenia
     * 
     */
    SI,

    /**
     * Slovakia
     * 
     */
    SK,

    /**
     * Sierra Leone
     * 
     */
    SL,

    /**
     * San Marino
     * 
     */
    SM,

    /**
     * Senegal
     * 
     */
    SN,

    /**
     * Somalia
     * 
     */
    SO,

    /**
     * Suriname
     * 
     */
    SR,

    /**
     * South Sudan
     * 
     */
    SS,

    /**
     * Sao Tome and Principe
     * 
     */
    ST,

    /**
     * El Salvador
     * 
     */
    SV,

    /**
     * Sint Maarten (Dutch part)
     * 
     */
    SX,

    /**
     * Syrian Arab Republic
     * 
     */
    SY,

    /**
     * Swaziland
     * 
     */
    SZ,

    /**
     * Turks and Caicos Islands
     * 
     */
    TC,

    /**
     * Chad
     * 
     */
    TD,

    /**
     * Togo
     * 
     */
    TG,

    /**
     * Thailand
     * 
     */
    TH,

    /**
     * Tajikistan
     * 
     */
    TJ,

    /**
     * Timor-Leste
     * 
     */
    TL,

    /**
     * Turkmenistan
     * 
     */
    TM,

    /**
     * Tunisia
     * 
     */
    TN,

    /**
     * Tonga
     * 
     */
    TO,

    /**
     * Turkey
     * 
     */
    TR,

    /**
     * Trinidad and Tobago
     * 
     */
    TT,

    /**
     * Tuvalu
     * 
     */
    TV,

    /**
     * Taiwan, Province of China
     * 
     */
    TW,

    /**
     * United Republic of Tanzania
     * 
     */
    TZ,

    /**
     * Ukraine
     * 
     */
    UA,

    /**
     * Uganda
     * 
     */
    UG,

    /**
     * United States of America
     * 
     */
    US,

    /**
     * Uruguay
     * 
     */
    UY,

    /**
     * Uzbekistan
     * 
     */
    UZ,

    /**
     * Holy See
     * 
     */
    VA,

    /**
     * Saint Vincent and the Grenadines
     * 
     */
    VC,

    /**
     * Bolivarian Republic of Venezuela
     * 
     */
    VE,

    /**
     * Virgin Islands (British)
     * 
     */
    VG,

    /**
     * Viet Nam
     * 
     */
    VN,

    /**
     * Vanuatu
     * 
     */
    VU,

    /**
     * World Intellectual Property Organization (WIPO) (International Bureau of)
     * 
     */
    WO,

    /**
     * Samoa
     * 
     */
    WS,

    /**
     * Nordic Patent Institute (NPI)
     * 
     */
    XN,

    /**
     * Yemen
     * 
     */
    YE,

    /**
     * South Africa
     * 
     */
    ZA,

    /**
     * Zambia
     * 
     */
    ZM,

    /**
     * Zimbabwe
     * 
     */
    ZW;

    public String value() {
        return name();
    }

    public static WIPOST3CodeType fromValue(String v) {
        return valueOf(v);
    }

}
