//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.03.11 at 12:27:12 AM CET 
//


package jxml;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for WordMarkSpecificationType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="WordMarkSpecificationType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="MarkVerbalElementText" type="{http://www.oami.europa.eu/TM-Search}TextType" minOccurs="0"/>
 *         &lt;element name="MarkStandardCharacterIndicator" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "WordMarkSpecificationType", propOrder = {
    "markVerbalElementText",
    "markStandardCharacterIndicator"
})
public class WordMarkSpecificationType {

    @XmlElement(name = "MarkVerbalElementText")
    protected TextType markVerbalElementText;
    @XmlElement(name = "MarkStandardCharacterIndicator")
    protected Boolean markStandardCharacterIndicator;

    /**
     * Gets the value of the markVerbalElementText property.
     * 
     * @return
     *     possible object is
     *     {@link TextType }
     *     
     */
    public TextType getMarkVerbalElementText() {
        return markVerbalElementText;
    }

    /**
     * Sets the value of the markVerbalElementText property.
     * 
     * @param value
     *     allowed object is
     *     {@link TextType }
     *     
     */
    public void setMarkVerbalElementText(TextType value) {
        this.markVerbalElementText = value;
    }

    /**
     * Gets the value of the markStandardCharacterIndicator property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isMarkStandardCharacterIndicator() {
        return markStandardCharacterIndicator;
    }

    /**
     * Sets the value of the markStandardCharacterIndicator property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setMarkStandardCharacterIndicator(Boolean value) {
        this.markStandardCharacterIndicator = value;
    }

}
